# Install spotipy library to play with Spotify develop data

In [2]:
#pip install spotipy

In [3]:
import json, os
from dotenv import load_dotenv
load_dotenv()

with open(".spotify_token_cache") as f:
    token_info = json.load(f)

payload = {
    "client_id": os.getenv("SPOTIPY_CLIENT_ID"),
    "client_secret": os.getenv("SPOTIPY_CLIENT_SECRET"),
    "token_info": token_info,
}

with open("secret_payload.json", "w") as f:
    json.dump(payload, f)
print("Created secret_payload.json")

Created secret_payload.json

Using the OAuth we are sending a login request by opening the browser and once if any user gives access then we are with that user.

In [4]:
import os
from dotenv import load_dotenv
import spotipy
from spotipy.oauth2 import SpotifyOAuth

print("Loaded .env:", load_dotenv())

sp = spotipy.Spotify(auth_manager=SpotifyOAuth(
    scope="playlist-read-private playlist-read-collaborative",
    open_browser=True,
    cache_path=".spotify_token_cache",
))

me = sp.current_user()
print("Logged in as:", me["display_name"], "|", me["id"])

Loaded .env: True
Logged in as: Tapasswin Manchala | 31j6r2v55c4av5hw3asmunoird2q

In [26]:
# current_user_playlists will give you the playlists of the user who logged in.
results = sp.current_user_playlists(limit=50)
for p in results["items"]:
    print(p["id"], "|", p["name"], "| owner:", p["owner"]["id"])

2HUtssXxSsShrf5enNLJbx | No Chill | owner: 31scqq5kysq43lokmssicfp3lhua
4djn8E11IAtL4MtCZ68exk | Motivation | owner: 31scqq5kysq43lokmssicfp3lhua
1LElxqeCMU38gSY6PKJOuY | My devotion | owner: 31j6r2v55c4av5hw3asmunoird2q
5Sy0vFMwVBfbw8dIez7oIV | Manisha | owner: 31j6r2v55c4av5hw3asmunoird2q

In [27]:
results["items"][3]["id"]  # This will give you the ID of the third playlist in the list.

'5Sy0vFMwVBfbw8dIez7oIV'

In [28]:
playlist_id = results["items"][3]["id"]  # from Cell 3 or your own playlist's link

items = []
results = sp.playlist_items(playlist_id, limit=100)
items.extend(results["items"])
while results["next"]:
    results = sp.next(results)
    items.extend(results["items"])

print(len(items), "items fetched")

183 items fetched

In [8]:
# Here is the list of the 
print(results)

{'href': 'https://api.spotify.com/v1/playlists/5Sy0vFMwVBfbw8dIez7oIV/items?offset=100&limit=100&additional_types=track', 'items': [{'added_at': '2024-08-18T16:09:43Z', 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/31j6r2v55c4av5hw3asmunoird2q'}, 'href': 'https://api.spotify.com/v1/users/31j6r2v55c4av5hw3asmunoird2q', 'id': '31j6r2v55c4av5hw3asmunoird2q', 'type': 'user', 'uri': 'spotify:user:31j6r2v55c4av5hw3asmunoird2q'}, 'is_local': False, 'primary_color': None, 'item': {'is_playable': True, 'explicit': False, 'type': 'track', 'episode': False, 'track': True, 'album': {'is_playable': True, 'type': 'album', 'album_type': 'single', 'href': 'https://api.spotify.com/v1/albums/2eASY2UZa4O8pdXvK9SNgC', 'id': '2eASY2UZa4O8pdXvK9SNgC', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b273d85f8f742deed1eb4bbec0dc', 'width': 640}, {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e02d85f8f742deed1eb4bbec0dc', 'width': 300}, {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d00004851d85f8f742deed1eb4bbec0dc', 'width': 64}], 'name': 'Chandamama', 'release_date': '2007-09-06', 'release_date_precision': 'day', 'uri': 'spotify:album:2eASY2UZa4O8pdXvK9SNgC', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/579pH2PjdCVSkAyFBv2Z8g'}, 'href': 'https://api.spotify.com/v1/artists/579pH2PjdCVSkAyFBv2Z8g', 'id': '579pH2PjdCVSkAyFBv2Z8g', 'name': 'K M Radhakrishnan', 'type': 'artist', 'uri': 'spotify:artist:579pH2PjdCVSkAyFBv2Z8g'}], 'external_urls': {'spotify': 'https://open.spotify.com/album/2eASY2UZa4O8pdXvK9SNgC'}, 'total_tracks': 6}, 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5as8A4G47Ohu9NSWs3Je8U'}, 'href': 'https://api.spotify.com/v1/artists/5as8A4G47Ohu9NSWs3Je8U', 'id': '5as8A4G47Ohu9NSWs3Je8U', 'name': 'Asha Bhosle', 'type': 'artist', 'uri': 'spotify:artist:5as8A4G47Ohu9NSWs3Je8U'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/579pH2PjdCVSkAyFBv2Z8g'}, 'href': 'https://api.spotify.com/v1/artists/579pH2PjdCVSkAyFBv2Z8g', 'id': '579pH2PjdCVSkAyFBv2Z8g', 'name': 'K M Radhakrishnan', 'type': 'artist', 'uri': 'spotify:artist:579pH2PjdCVSkAyFBv2Z8g'}], 'disc_number': 1, 'track_number': 4, 'duration_ms': 273776, 'external_ids': {'isrc': 'INA090930421'}, 'external_urls': {'spotify': 'https://open.spotify.com/track/32faUN4IsCs1wk1ljIQr9C'}, 'href': 'https://api.spotify.com/v1/tracks/32faUN4IsCs1wk1ljIQr9C', 'id': '32faUN4IsCs1wk1ljIQr9C', 'name': 'Naalo Oohalaku', 'uri': 'spotify:track:32faUN4IsCs1wk1ljIQr9C', 'is_local': False}, 'video_thumbnail': {'url': None}}, {'added_at': '2024-08-18T16:09:46Z', 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/31j6r2v55c4av5hw3asmunoird2q'}, 'href': 'https://api.spotify.com/v1/users/31j6r2v55c4av5hw3asmunoird2q', 'id': '31j6r2v55c4av5hw3asmunoird2q', 'type': 'user', 'uri': 'spotify:user:31j6r2v55c4av5hw3asmunoird2q'}, 'is_local': False, 'primary_color': None, 'item': {'is_playable': True, 'explicit': False, 'type': 'track', 'episode': False, 'track': True, 'album': {'is_playable': True, 'type': 'album', 'album_type': 'single', 'href': 'https://api.spotify.com/v1/albums/2eASY2UZa4O8pdXvK9SNgC', 'id': '2eASY2UZa4O8pdXvK9SNgC', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b273d85f8f742deed1eb4bbec0dc', 'width': 640}, {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e02d85f8f742deed1eb4bbec0dc', 'width': 300}, {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d00004851d85f8f742deed1eb4bbec0dc', 'width': 64}], 'name': 'Chandamama', 'release_date': '2007-09-06', 'release_date_precision': 'day', 'uri': 'spotify:album:2eASY2UZa4O8pdXvK9SNgC', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/579pH2PjdCVSkAyFBv2Z8g'}, 'href': 'https://api.spotify.com/v1/artists/579pH2PjdCVSkAyFBv2Z8g', 'id': '579pH2PjdCVSkAyFBv2Z8g', 'name': 'K M Radhakrishnan', 'type': 'artist', 'uri': 'spotify:artist:579pH2PjdCVSkAyFBv2Z8g'}], 'external_urls': {'spotify': 'https://open.spotify.com/album/2eASY2UZa4O8pdXvK9SNgC'}, 'total_tracks': 6}, 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/0BDs2eNYNZvlMnnlijsfoL'}, 'href': 'https://api.spotify.com/v1/artists/0BDs2eNYNZvlMnnlijsfoL', 'id': '0BDs2eNYNZvlMnnlijsfoL', 'name': 'Jessi Gift', 'type': 'artist', 'uri': 'spotify:artist:0BDs2eNYNZvlMnnlijsfoL'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/3QL2xVnI7n5Fng1l4e56AP'}, 'href': 'https://api.spotify.com/v1/artists/3QL2xVnI7n5Fng1l4e56AP', 'id': '3QL2xVnI7n5Fng1l4e56AP', 'name': 'Mamta Mohandas', 'type': 'artist', 'uri': 'spotify:artist:3QL2xVnI7n5Fng1l4e56AP'}], 'disc_number': 1, 'track_number': 5, 'duration_ms': 274454, 'external_ids': {'isrc': 'INA090930422'}, 'external_urls': {'spotify': 'https://open.spotify.com/track/4yDzLrYRH1vMSI1qjR8ymb'}, 'href': 'https://api.spotify.com/v1/tracks/4yDzLrYRH1vMSI1qjR8ymb', 'id': '4yDzLrYRH1vMSI1qjR8ymb', 'name': 'Sakkubayiney', 'uri': 'spotify:track:4yDzLrYRH1vMSI1qjR8ymb', 'is_local': False}, 'video_thumbnail': {'url': None}}, {'added_at': '2024-08-18T16:09:50Z', 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/31j6r2v55c4av5hw3asmunoird2q'}, 'href': 'https://api.spotify.com/v1/users/31j6r2v55c4av5hw3asmunoird2q', 'id': '31j6r2v55c4av5hw3asmunoird2q', 'type': 'user', 'uri': 'spotify:user:31j6r2v55c4av5hw3asmunoird2q'}, 'is_local': False, 'primary_color': None, 'item': {'is_playable': True, 'explicit': False, 'type': 'track', 'episode': False, 'track': True, 'album': {'is_playable': True, 'type': 'album', 'album_type': 'single', 'href': 'https://api.spotify.com/v1/albums/2eASY2UZa4O8pdXvK9SNgC', 'id': '2eASY2UZa4O8pdXvK9SNgC', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b273d85f8f742deed1eb4bbec0dc', 'width': 640}, {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e02d85f8f742deed1eb4bbec0dc', 'width': 300}, {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d00004851d85f8f742deed1eb4bbec0dc', 'width': 64}], 'name': 'Chandamama', 'release_date': '2007-09-06', 'release_date_precision': 'day', 'uri': 'spotify:album:2eASY2UZa4O8pdXvK9SNgC', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/579pH2PjdCVSkAyFBv2Z8g'}, 'href': 'https://api.spotify.com/v1/artists/579pH2PjdCVSkAyFBv2Z8g', 'id': '579pH2PjdCVSkAyFBv2Z8g', 'name': 'K M Radhakrishnan', 'type': 'artist', 'uri': 'spotify:artist:579pH2PjdCVSkAyFBv2Z8g'}], 'external_urls': {'spotify': 'https://open.spotify.com/album/2eASY2UZa4O8pdXvK9SNgC'}, 'total_tracks': 6}, 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1QvyquqkuuwUzdszyoKIy4'}, 'href': 'https://api.spotify.com/v1/artists/1QvyquqkuuwUzdszyoKIy4', 'id': '1QvyquqkuuwUzdszyoKIy4', 'name': 'Haricharan', 'type': 'artist', 'uri': 'spotify:artist:1QvyquqkuuwUzdszyoKIy4'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/2JEjaa7hWhE1BbL3OcoeFR'}, 'href': 'https://api.spotify.com/v1/artists/2JEjaa7hWhE1BbL3OcoeFR', 'id': '2JEjaa7hWhE1BbL3OcoeFR', 'name': 'Sujatha', 'type': 'artist', 'uri': 'spotify:artist:2JEjaa7hWhE1BbL3OcoeFR'}], 'disc_number': 1, 'track_number': 6, 'duration_ms': 278864, 'external_ids': {'isrc': 'INA090930423'}, 'external_urls': {'spotify': 'https://open.spotify.com/track/1DPRAIq9V0r2UPw4xA1iFf'}, 'href': 'https://api.spotify.com/v1/tracks/1DPRAIq9V0r2UPw4xA1iFf', 'id': '1DPRAIq9V0r2UPw4xA1iFf', 'name': 'Mukku Pye Muddu', 'uri': 'spotify:track:1DPRAIq9V0r2UPw4xA1iFf', 'is_local': False}, 'video_thumbnail': {'url': None}}, {'added_at': '2024-08-18T16:10:00Z', 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/31j6r2v55c4av5hw3asmunoird2q'}, 'href': 'https://api.spotify.com/v1/users/31j6r2v55c4av5hw3asmunoird2q', 'id': '31j6r2v55c4av5hw3asmunoird2q', 'type': 'user', 'uri': 'spotify:user:31j6r2v55c4av5hw3asmunoird2q'}, 'is_local': False, 'primary_color': None, 'item': {'is_playable': True, 'explicit': False, 'type': 'track', 'episode': False, 'track': True, 'album': {'is_playable': True, 'type': 'album', 'album_type': 'album', 'href': 'https://api.spotify.com/v1/albums/0oqXFsTVJInCqJJJAn7wel', 'id': '0oqXFsTVJInCqJJJAn7wel', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b2731dea2aa9556b19a62d38eb1c', 'width': 640}, {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e021dea2aa9556b19a62d38eb1c', 'width': 300}, {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d000048511dea2aa9556b19a62d38eb1c', 'width': 64}], 'name': 'Radhe Shyam (Telugu)', 'release_date': '2022-03-12', 'release_date_precision': 'day', 'uri': 'spotify:album:0oqXFsTVJInCqJJJAn7wel', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3ocTwOjekTkFdD695eKuQr'}, 'href': 'https://api.spotify.com/v1/artists/3ocTwOjekTkFdD695eKuQr', 'id': '3ocTwOjekTkFdD695eKuQr', 'name': 'Justin Prabhakaran', 'type': 'artist', 'uri': 'spotify:artist:3ocTwOjekTkFdD695eKuQr'}], 'external_urls': {'spotify': 'https://open.spotify.com/album/0oqXFsTVJInCqJJJAn7wel'}, 'total_tracks': 7}, 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/4zCH9qm4R2DADamUHMCa6O'}, 'href': 'https://api.spotify.com/v1/artists/4zCH9qm4R2DADamUHMCa6O', 'id': '4zCH9qm4R2DADamUHMCa6O', 'name': 'Anirudh Ravichander', 'type': 'artist', 'uri': 'spotify:artist:4zCH9qm4R2DADamUHMCa6O'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/3ocTwOjekTkFdD695eKuQr'}, 'href': 'https://api.spotify.com/v1/artists/3ocTwOjekTkFdD695eKuQr', 'id': '3ocTwOjekTkFdD695eKuQr', 'name': 'Justin Prabhakaran', 'type': 'artist', 'uri': 'spotify:artist:3ocTwOjekTkFdD695eKuQr'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/2yvOLf1gt6m9qPgzzqpxQx'}, 'href': 'https://api.spotify.com/v1/artists/2yvOLf1gt6m9qPgzzqpxQx', 'id': '2yvOLf1gt6m9qPgzzqpxQx', 'name': 'Krishna Kanth', 'type': 'artist', 'uri': 'spotify:artist:2yvOLf1gt6m9qPgzzqpxQx'}], 'disc_number': 1, 'track_number': 1, 'duration_ms': 268000, 'external_ids': {'isrc': 'INS182116119'}, 'external_urls': {'spotify': 'https://open.spotify.com/track/5C8b6OQlsIOtpbf6DCBkKk'}, 'href': 'https://api.spotify.com/v1/tracks/5C8b6OQlsIOtpbf6DCBkKk', 'id': '5C8b6OQlsIOtpbf6DCBkKk', 'name': 'Sanchari', 'uri': 'spotify:track:5C8b6OQlsIOtpbf6DCBkKk', 'is_local': False}, 'video_thumbnail': {'url': None}}, {'added_at': '2024-08-18T16:10:04Z', 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/31j6r2v55c4av5hw3asmunoird2q'}, 'href': 'https://api.spotify.com/v1/users/31j6r2v55c4av5hw3asmunoird2q', 'id': '31j6r2v55c4av5hw3asmunoird2q', 'type': 'user', 'uri': 'spotify:user:31j6r2v55c4av5hw3asmunoird2q'}, 'is_local': False, 'primary_color': None, 'item': {'is_playable': True, 'explicit': False, 'type': 'track', 'episode': False, 'track': True, 'album': {'is_playable': True, 'type': 'album', 'album_type': 'album', 'href': 'https://api.spotify.com/v1/albums/0oqXFsTVJInCqJJJAn7wel', 'id': '0oqXFsTVJInCqJJJAn7wel', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b2731dea2aa9556b19a62d38eb1c', 'width': 640}, {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e021dea2aa9556b19a62d38eb1c', 'width': 300}, {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d000048511dea2aa9556b19a62d38eb1c', 'width': 64}], 'name': 'Radhe Shyam (Telugu)', 'release_date': '2022-03-12', 'release_date_precision': 'day', 'uri': 'spotify:album:0oqXFsTVJInCqJJJAn7wel', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3ocTwOjekTkFdD695eKuQr'}, 'href': 'https://api.spotify.com/v1/artists/3ocTwOjekTkFdD695eKuQr', 'id': '3ocTwOjekTkFdD695eKuQr', 'name': 'Justin Prabhakaran', 'type': 'artist', 'uri': 'spotify:artist:3ocTwOjekTkFdD695eKuQr'}], 'external_urls': {'spotify': 'https://open.spotify.com/album/0oqXFsTVJInCqJJJAn7wel'}, 'total_tracks': 7}, 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/7qjJw7ZM2ekDSahLXPjIlN'}, 'href': 'https://api.spotify.com/v1/artists/7qjJw7ZM2ekDSahLXPjIlN', 'id': '7qjJw7ZM2ekDSahLXPjIlN', 'name': 'Sid Sriram', 'type': 'artist', 'uri': 'spotify:artist:7qjJw7ZM2ekDSahLXPjIlN'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/3ocTwOjekTkFdD695eKuQr'}, 'href': 'https://api.spotify.com/v1/artists/3ocTwOjekTkFdD695eKuQr', 'id': '3ocTwOjekTkFdD695eKuQr', 'name': 'Justin Prabhakaran', 'type': 'artist', 'uri': 'spotify:artist:3ocTwOjekTkFdD695eKuQr'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/2yvOLf1gt6m9qPgzzqpxQx'}, 'href': 'https://api.spotify.com/v1/artists/2yvOLf1gt6m9qPgzzqpxQx', 'id': '2yvOLf1gt6m9qPgzzqpxQx', 'name': 'Krishna Kanth', 'type': 'artist', 'uri': 'spotify:artist:2yvOLf1gt6m9qPgzzqpxQx'}], 'disc_number': 1, 'track_number': 2, 'duration_ms': 294115, 'external_ids': {'isrc': 'INS182115843'}, 'external_urls': {'spotify': 'https://open.spotify.com/track/56dpwomaj1YnKZ0L4b33hN'}, 'href': 'https://api.spotify.com/v1/tracks/56dpwomaj1YnKZ0L4b33hN', 'id': '56dpwomaj1YnKZ0L4b33hN', 'name': 'Nagumomu Thaarale', 'uri': 'spotify:track:56dpwomaj1YnKZ0L4b33hN', 'is_local': False}, 'video_thumbnail': {'url': None}}, {'added_at': '2024-08-18T16:10:10Z', 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/31j6r2v55c4av5hw3asmunoird2q'}, 'href': 'https://api.spotify.com/v1/users/31j6r2v55c4av5hw3asmunoird2q', 'id': '31j6r2v55c4av5hw3asmunoird2q', 'type': 'user', 'uri': 'spotify:user:31j6r2v55c4av5hw3asmunoird2q'}, 'is_local': False, 'primary_color': None, 'item': {'is_playable': True, 'explicit': False, 'type': 'track', 'episode': False, 'track': True, 'album': {'is_playable': True, 'type': 'album', 'album_type': 'album', 'href': 'https://api.spotify.com/v1/albums/0oqXFsTVJInCqJJJAn7wel', 'id': '0oqXFsTVJInCqJJJAn7wel', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b2731dea2aa9556b19a62d38eb1c', 'width': 640}, {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e021dea2aa9556b19a62d38eb1c', 'width': 300}, {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d000048511dea2aa9556b19a62d38eb1c', 'width': 64}], 'name': 'Radhe Shyam (Telugu)', 'release_date': '2022-03-12', 'release_date_precision': 'day', 'uri': 'spotify:album:0oqXFsTVJInCqJJJAn7wel', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3ocTwOjekTkFdD695eKuQr'}, 'href': 'https://api.spotify.com/v1/artists/3ocTwOjekTkFdD695eKuQr', 'id': '3ocTwOjekTkFdD695eKuQr', 'name': 'Justin Prabhakaran', 'type': 'artist', 'uri': 'spotify:artist:3ocTwOjekTkFdD695eKuQr'}], 'external_urls': {'spotify': 'https://open.spotify.com/album/0oqXFsTVJInCqJJJAn7wel'}, 'total_tracks': 7}, 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/6AiX12wXdXFoGJ2vk8zBjy'}, 'href': 'https://api.spotify.com/v1/artists/6AiX12wXdXFoGJ2vk8zBjy', 'id': '6AiX12wXdXFoGJ2vk8zBjy', 'name': 'Yuvan Shankar Raja', 'type': 'artist', 'uri': 'spotify:artist:6AiX12wXdXFoGJ2vk8zBjy'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/1lr0MlyZ8Q24eFtn7gcMmI'}, 'href': 'https://api.spotify.com/v1/artists/1lr0MlyZ8Q24eFtn7gcMmI', 'id': '1lr0MlyZ8Q24eFtn7gcMmI', 'name': 'Harini Ivaturi', 'type': 'artist', 'uri': 'spotify:artist:1lr0MlyZ8Q24eFtn7gcMmI'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/3ocTwOjekTkFdD695eKuQr'}, 'href': 'https://api.spotify.com/v1/artists/3ocTwOjekTkFdD695eKuQr', 'id': '3ocTwOjekTkFdD695eKuQr', 'name': 'Justin Prabhakaran', 'type': 'artist', 'uri': 'spotify:artist:3ocTwOjekTkFdD695eKuQr'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/2yvOLf1gt6m9qPgzzqpxQx'}, 'href': 'https://api.spotify.com/v1/artists/2yvOLf1gt6m9qPgzzqpxQx', 'id': '2yvOLf1gt6m9qPgzzqpxQx', 'name': 'Krishna Kanth', 'type': 'artist', 'uri': 'spotify:artist:2yvOLf1gt6m9qPgzzqpxQx'}], 'disc_number': 1, 'track_number': 3, 'duration_ms': 232762, 'external_ids': {'isrc': 'INS182115645'}, 'external_urls': {'spotify': 'https://open.spotify.com/track/77feKtBcyhRv4SE2u6dd9R'}, 'href': 'https://api.spotify.com/v1/tracks/77feKtBcyhRv4SE2u6dd9R', 'id': '77feKtBcyhRv4SE2u6dd9R', 'name': 'Ee Raathale', 'uri': 'spotify:track:77feKtBcyhRv4SE2u6dd9R', 'is_local': False}, 'video_thumbnail': {'url': None}}, {'added_at': '2024-08-18T16:10:14Z', 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/31j6r2v55c4av5hw3asmunoird2q'}, 'href': 'https://api.spotify.com/v1/users/31j6r2v55c4av5hw3asmunoird2q', 'id': '31j6r2v55c4av5hw3asmunoird2q', 'type': 'user', 'uri': 'spotify:user:31j6r2v55c4av5hw3asmunoird2q'}, 'is_local': False, 'primary_color': None, 'item': {'is_playable': True, 'explicit': False, 'type': 'track', 'episode': False, 'track': True, 'album': {'is_playable': True, 'type': 'album', 'album_type': 'album', 'href': 'https://api.spotify.com/v1/albums/0oqXFsTVJInCqJJJAn7wel', 'id': '0oqXFsTVJInCqJJJAn7wel', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b2731dea2aa9556b19a62d38eb1c', 'width': 640}, {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e021dea2aa9556b19a62d38eb1c', 'width': 300}, {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d000048511dea2aa9556b19a62d38eb1c', 'width': 64}], 'name': 'Radhe Shyam (Telugu)', 'release_date': '2022-03-12', 'release_date_precision': 'day', 'uri': 'spotify:album:0oqXFsTVJInCqJJJAn7wel', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3ocTwOjekTkFdD695eKuQr'}, 'href': 'https://api.spotify.com/v1/artists/3ocTwOjekTkFdD695eKuQr', 'id': '3ocTwOjekTkFdD695eKuQr', 'name': 'Justin Prabhakaran', 'type': 'artist', 'uri': 'spotify:artist:3ocTwOjekTkFdD695eKuQr'}], 'external_urls': {'spotify': 'https://open.spotify.com/album/0oqXFsTVJInCqJJJAn7wel'}, 'total_tracks': 7}, 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/6LWyVEIBnx7MoRBhQxu9om'}, 'href': 'https://api.spotify.com/v1/artists/6LWyVEIBnx7MoRBhQxu9om', 'id': '6LWyVEIBnx7MoRBhQxu9om', 'name': 'Anurag Kulkarni', 'type': 'artist', 'uri': 'spotify:artist:6LWyVEIBnx7MoRBhQxu9om'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/0oOet2f43PA68X5RxKobEy'}, 'href': 'https://api.spotify.com/v1/artists/0oOet2f43PA68X5RxKobEy', 'id': '0oOet2f43PA68X5RxKobEy', 'name': 'Shreya Ghoshal', 'type': 'artist', 'uri': 'spotify:artist:0oOet2f43PA68X5RxKobEy'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/3ocTwOjekTkFdD695eKuQr'}, 'href': 'https://api.spotify.com/v1/artists/3ocTwOjekTkFdD695eKuQr', 'id': '3ocTwOjekTkFdD695eKuQr', 'name': 'Justin Prabhakaran', 'type': 'artist', 'uri': 'spotify:artist:3ocTwOjekTkFdD695eKuQr'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/2yvOLf1gt6m9qPgzzqpxQx'}, 'href': 'https://api.spotify.com/v1/artists/2yvOLf1gt6m9qPgzzqpxQx', 'id': '2yvOLf1gt6m9qPgzzqpxQx', 'name': 'Krishna Kanth', 'type': 'artist', 'uri': 'spotify:artist:2yvOLf1gt6m9qPgzzqpxQx'}], 'disc_number': 1, 'track_number': 4, 'duration_ms': 240070, 'external_ids': {'isrc': 'INS182200017'}, 'external_urls': {'spotify': 'https://open.spotify.com/track/7uo3wgB8We99kdcJpKDiq9'}, 'href': 'https://api.spotify.com/v1/tracks/7uo3wgB8We99kdcJpKDiq9', 'id': '7uo3wgB8We99kdcJpKDiq9', 'name': 'Ninnele', 'uri': 'spotify:track:7uo3wgB8We99kdcJpKDiq9', 'is_local': False}, 'video_thumbnail': {'url': None}}, {'added_at': '2024-08-18T16:10:18Z', 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/31j6r2v55c4av5hw3asmunoird2q'}, 'href': 'https://api.spotify.com/v1/users/31j6r2v55c4av5hw3asmunoird2q', 'id': '31j6r2v55c4av5hw3asmunoird2q', 'type': 'user', 'uri': 'spotify:user:31j6r2v55c4av5hw3asmunoird2q'}, 'is_local': False, 'primary_color': None, 'item': {'is_playable': True, 'explicit': False, 'type': 'track', 'episode': False, 'track': True, 'album': {'is_playable': True, 'type': 'album', 'album_type': 'album', 'href': 'https://api.spotify.com/v1/albums/0oqXFsTVJInCqJJJAn7wel', 'id': '0oqXFsTVJInCqJJJAn7wel', 'images': [{'height': 640, '

In [9]:
print(results['items'][0]['item']['album']['id'])
print(results['items'][0]['item']['album']['name'])
print(results['items'][0]['item']['album']['release_date'])
print(results['items'][0]['item']['external_urls']['spotify'])
print(results['items'][0]['item']['artists'][0]['name'])
print(results['items'][0]['item']['name'])

2eASY2UZa4O8pdXvK9SNgC
Chandamama
2007-09-06
https://open.spotify.com/track/32faUN4IsCs1wk1ljIQr9C
Asha Bhosle
Naalo Oohalaku

In [10]:
print(results['items'][0])

{'added_at': '2024-08-18T16:09:43Z', 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/31j6r2v55c4av5hw3asmunoird2q'}, 'href': 'https://api.spotify.com/v1/users/31j6r2v55c4av5hw3asmunoird2q', 'id': '31j6r2v55c4av5hw3asmunoird2q', 'type': 'user', 'uri': 'spotify:user:31j6r2v55c4av5hw3asmunoird2q'}, 'is_local': False, 'primary_color': None, 'item': {'is_playable': True, 'explicit': False, 'type': 'track', 'episode': False, 'track': True, 'album': {'is_playable': True, 'type': 'album', 'album_type': 'single', 'href': 'https://api.spotify.com/v1/albums/2eASY2UZa4O8pdXvK9SNgC', 'id': '2eASY2UZa4O8pdXvK9SNgC', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b273d85f8f742deed1eb4bbec0dc', 'width': 640}, {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e02d85f8f742deed1eb4bbec0dc', 'width': 300}, {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d00004851d85f8f742deed1eb4bbec0dc', 'width': 64}], 'name': 'Chandamama', 'release_date': '2007-09-06', 'release_date_precision': 'day', 'uri': 'spotify:album:2eASY2UZa4O8pdXvK9SNgC', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/579pH2PjdCVSkAyFBv2Z8g'}, 'href': 'https://api.spotify.com/v1/artists/579pH2PjdCVSkAyFBv2Z8g', 'id': '579pH2PjdCVSkAyFBv2Z8g', 'name': 'K M Radhakrishnan', 'type': 'artist', 'uri': 'spotify:artist:579pH2PjdCVSkAyFBv2Z8g'}], 'external_urls': {'spotify': 'https://open.spotify.com/album/2eASY2UZa4O8pdXvK9SNgC'}, 'total_tracks': 6}, 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5as8A4G47Ohu9NSWs3Je8U'}, 'href': 'https://api.spotify.com/v1/artists/5as8A4G47Ohu9NSWs3Je8U', 'id': '5as8A4G47Ohu9NSWs3Je8U', 'name': 'Asha Bhosle', 'type': 'artist', 'uri': 'spotify:artist:5as8A4G47Ohu9NSWs3Je8U'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/579pH2PjdCVSkAyFBv2Z8g'}, 'href': 'https://api.spotify.com/v1/artists/579pH2PjdCVSkAyFBv2Z8g', 'id': '579pH2PjdCVSkAyFBv2Z8g', 'name': 'K M Radhakrishnan', 'type': 'artist', 'uri': 'spotify:artist:579pH2PjdCVSkAyFBv2Z8g'}], 'disc_number': 1, 'track_number': 4, 'duration_ms': 273776, 'external_ids': {'isrc': 'INA090930421'}, 'external_urls': {'spotify': 'https://open.spotify.com/track/32faUN4IsCs1wk1ljIQr9C'}, 'href': 'https://api.spotify.com/v1/tracks/32faUN4IsCs1wk1ljIQr9C', 'id': '32faUN4IsCs1wk1ljIQr9C', 'name': 'Naalo Oohalaku', 'uri': 'spotify:track:32faUN4IsCs1wk1ljIQr9C', 'is_local': False}, 'video_thumbnail': {'url': None}}

# Extracting Album

In [11]:
album = []

for item in results['items']:
    album_id = item['item']['album']['id']
    album_name = item['item']['album']['name']
    album_release_date = item['item']['album']['release_date']
    album_total_tracks = item['item']['album']['total_tracks']
    album_spotify_url = item['item']['external_urls']['spotify']

    album_elements = {
        'album_id': album_id,
        'album_name': album_name,
        'album_release_date': album_release_date,
        'album_total_tracks': album_total_tracks,
        'album_spotify_url': album_spotify_url
    }
    album.append(album_elements)

In [12]:
print(album)

[{'album_id': '2eASY2UZa4O8pdXvK9SNgC', 'album_name': 'Chandamama', 'album_release_date': '2007-09-06', 'album_total_tracks': 6, 'album_spotify_url': 'https://open.spotify.com/track/32faUN4IsCs1wk1ljIQr9C'}, {'album_id': '2eASY2UZa4O8pdXvK9SNgC', 'album_name': 'Chandamama', 'album_release_date': '2007-09-06', 'album_total_tracks': 6, 'album_spotify_url': 'https://open.spotify.com/track/4yDzLrYRH1vMSI1qjR8ymb'}, {'album_id': '2eASY2UZa4O8pdXvK9SNgC', 'album_name': 'Chandamama', 'album_release_date': '2007-09-06', 'album_total_tracks': 6, 'album_spotify_url': 'https://open.spotify.com/track/1DPRAIq9V0r2UPw4xA1iFf'}, {'album_id': '0oqXFsTVJInCqJJJAn7wel', 'album_name': 'Radhe Shyam (Telugu)', 'album_release_date': '2022-03-12', 'album_total_tracks': 7, 'album_spotify_url': 'https://open.spotify.com/track/5C8b6OQlsIOtpbf6DCBkKk'}, {'album_id': '0oqXFsTVJInCqJJJAn7wel', 'album_name': 'Radhe Shyam (Telugu)', 'album_release_date': '2022-03-12', 'album_total_tracks': 7, 'album_spotify_url': 'https://open.spotify.com/track/56dpwomaj1YnKZ0L4b33hN'}, {'album_id': '0oqXFsTVJInCqJJJAn7wel', 'album_name': 'Radhe Shyam (Telugu)', 'album_release_date': '2022-03-12', 'album_total_tracks': 7, 'album_spotify_url': 'https://open.spotify.com/track/77feKtBcyhRv4SE2u6dd9R'}, {'album_id': '0oqXFsTVJInCqJJJAn7wel', 'album_name': 'Radhe Shyam (Telugu)', 'album_release_date': '2022-03-12', 'album_total_tracks': 7, 'album_spotify_url': 'https://open.spotify.com/track/7uo3wgB8We99kdcJpKDiq9'}, {'album_id': '0oqXFsTVJInCqJJJAn7wel', 'album_name': 'Radhe Shyam (Telugu)', 'album_release_date': '2022-03-12', 'album_total_tracks': 7, 'album_spotify_url': 'https://open.spotify.com/track/4oV0B47QAl5k3efL3K4Sih'}, {'album_id': '0oqXFsTVJInCqJJJAn7wel', 'album_name': 'Radhe Shyam (Telugu)', 'album_release_date': '2022-03-12', 'album_total_tracks': 7, 'album_spotify_url': 'https://open.spotify.com/track/6GMGQ7BkieCY0X0MpiDOC7'}, {'album_id': '0oqXFsTVJInCqJJJAn7wel', 'album_name': 'Radhe Shyam (Telugu)', 'album_release_date': '2022-03-12', 'album_total_tracks': 7, 'album_spotify_url': 'https://open.spotify.com/track/6e9k0zPtJfqJIseybAK2G0'}, {'album_id': '37evPVtdfVL0X4Sji9tQdu', 'album_name': 'Kushi', 'album_release_date': '2001-03-27', 'album_total_tracks': 6, 'album_spotify_url': 'https://open.spotify.com/track/1ha2Dvv2vVyIbQUBCtbKvQ'}, {'album_id': '37evPVtdfVL0X4Sji9tQdu', 'album_name': 'Kushi', 'album_release_date': '2001-03-27', 'album_total_tracks': 6, 'album_spotify_url': 'https://open.spotify.com/track/2YZZFwARteC3gM1aEgHHMr'}, {'album_id': '37evPVtdfVL0X4Sji9tQdu', 'album_name': 'Kushi', 'album_release_date': '2001-03-27', 'album_total_tracks': 6, 'album_spotify_url': 'https://open.spotify.com/track/0hwlEWBrraTWI9PTNzG0RJ'}, {'album_id': '37evPVtdfVL0X4Sji9tQdu', 'album_name': 'Kushi', 'album_release_date': '2001-03-27', 'album_total_tracks': 6, 'album_spotify_url': 'https://open.spotify.com/track/1llCrHsp3meUV30YTiTwpY'}, {'album_id': '37evPVtdfVL0X4Sji9tQdu', 'album_name': 'Kushi', 'album_release_date': '2001-03-27', 'album_total_tracks': 6, 'album_spotify_url': 'https://open.spotify.com/track/1pHttWyIwIbFu9vVjsjOUr'}, {'album_id': '37evPVtdfVL0X4Sji9tQdu', 'album_name': 'Kushi', 'album_release_date': '2001-03-27', 'album_total_tracks': 6, 'album_spotify_url': 'https://open.spotify.com/track/4DS8arJWnkpetpBg72P0nJ'}, {'album_id': '78bohc0Dzw7AoPpqVn9rsl', 'album_name': 'Kushi (Telugu)', 'album_release_date': '2023-08-29', 'album_total_tracks': 5, 'album_spotify_url': 'https://open.spotify.com/track/5ReOjb2X6TCkMfYoHuVW1b'}, {'album_id': '78bohc0Dzw7AoPpqVn9rsl', 'album_name': 'Kushi (Telugu)', 'album_release_date': '2023-08-29', 'album_total_tracks': 5, 'album_spotify_url': 'https://open.spotify.com/track/3nCqpSpwxuO4gYF1wGS6WM'}, {'album_id': '78bohc0Dzw7AoPpqVn9rsl', 'album_name': 'Kushi (Telugu)', 'album_release_date': '2023-08-29', 'album_total_tracks': 5, 'album_spotify_url': 'https://open.spotify.com/track/6Zp14O0N7iNLTrKYSOsOJh'}, {'album_id': '78bohc0Dzw7AoPpqVn9rsl', 'album_name': 'Kushi (Telugu)', 'album_release_date': '2023-08-29', 'album_total_tracks': 5, 'album_spotify_url': 'https://open.spotify.com/track/4uZ5kNUtXpb8B57taLXVyT'}, {'album_id': '78bohc0Dzw7AoPpqVn9rsl', 'album_name': 'Kushi (Telugu)', 'album_release_date': '2023-08-29', 'album_total_tracks': 5, 'album_spotify_url': 'https://open.spotify.com/track/36WCfBpLBpBKCzWB8pgvEj'}, {'album_id': '3loo3ZQ43Rsu0FdtorNZE0', 'album_name': 'DJ Tillu', 'album_release_date': '2022-01-06', 'album_total_tracks': 1, 'album_spotify_url': 'https://open.spotify.com/track/4ZNIkO2j6K2c0Nm8zWXmdn'}, {'album_id': '5oNL1ay25NKeMieYCFwhci', 'album_name': 'Tillu Square', 'album_release_date': '2023-07-26', 'album_total_tracks': 1, 'album_spotify_url': 'https://open.spotify.com/track/3NdQpAhK5s42vu3do3KSBT'}, {'album_id': '7ujJhfGKy2qKe2OBQqw173', 'album_name': 'Tillu Square', 'album_release_date': '2023-11-27', 'album_total_tracks': 1, 'album_spotify_url': 'https://open.spotify.com/track/0S9j9OAG3KjmBg4j9XzFcC'}, {'album_id': '7E7U9TkPPbPeAg4EnkdYW8', 'album_name': 'Tillu Square', 'album_release_date': '2024-03-18', 'album_total_tracks': 1, 'album_spotify_url': 'https://open.spotify.com/track/3nHm9xxmzEbLigsaigMhdk'}, {'album_id': '2KaGqPKoMOwa9jyDClvyZE', 'album_name': 'Nuvvu Leka Nenu Lenu (Original Motion Picture Soundtrack)', 'album_release_date': '2002-01-14', 'album_total_tracks': 7, 'album_spotify_url': 'https://open.spotify.com/track/5TbrSBo3ob5QLD9y0YowJZ'}, {'album_id': '2KaGqPKoMOwa9jyDClvyZE', 'album_name': 'Nuvvu Leka Nenu Lenu (Original Motion Picture Soundtrack)', 'album_release_date': '2002-01-14', 'album_total_tracks': 7, 'album_spotify_url': 'https://open.spotify.com/track/13sMxrwVZsewW7TWo0py5x'}, {'album_id': '2KaGqPKoMOwa9jyDClvyZE', 'album_name': 'Nuvvu Leka Nenu Lenu (Original Motion Picture Soundtrack)', 'album_release_date': '2002-01-14', 'album_total_tracks': 7, 'album_spotify_url': 'https://open.spotify.com/track/0dyKAXGZbr2YlYfGaxwlix'}, {'album_id': '2KaGqPKoMOwa9jyDClvyZE', 'album_name': 'Nuvvu Leka Nenu Lenu (Original Motion Picture Soundtrack)', 'album_release_date': '2002-01-14', 'album_total_tracks': 7, 'album_spotify_url': 'https://open.spotify.com/track/0GdqslyQxu5GcAQSggao0j'}, {'album_id': '2KaGqPKoMOwa9jyDClvyZE', 'album_name': 'Nuvvu Leka Nenu Lenu (Original Motion Picture Soundtrack)', 'album_release_date': '2002-01-14', 'album_total_tracks': 7, 'album_spotify_url': 'https://open.spotify.com/track/7DHZqJ8XQSEvIXs9BjriPU'}, {'album_id': '2KaGqPKoMOwa9jyDClvyZE', 'album_name': 'Nuvvu Leka Nenu Lenu (Original Motion Picture Soundtrack)', 'album_release_date': '2002-01-14', 'album_total_tracks': 7, 'album_spotify_url': 'https://open.spotify.com/track/5avXQ60kyevSUDcXJxiaMQ'}, {'album_id': '2KaGqPKoMOwa9jyDClvyZE', 'album_name': 'Nuvvu Leka Nenu Lenu (Original Motion Picture Soundtrack)', 'album_release_date': '2002-01-14', 'album_total_tracks': 7, 'album_spotify_url': 'https://open.spotify.com/track/08siM57VJCV7lGg6JWmB3s'}, {'album_id': '5d0eh1FoU7tOYEnHLohjjv', 'album_name': 'Sita Ramam (Telugu) (Extended Version) [Original Motion Picture Soundtrack]', 'album_release_date': '2022-09-08', 'album_total_tracks': 10, 'album_spotify_url': 'https://open.spotify.com/track/28xt5x1wwoMfVYI9zfIwRx'}, {'album_id': '5d0eh1FoU7tOYEnHLohjjv', 'album_name': 'Sita Ramam (Telugu) (Extended Version) [Original Motion Picture Soundtrack]', 'album_release_date': '2022-09-08', 'album_total_tracks': 10, 'album_spotify_url': 'https://open.spotify.com/track/2rDPTKSWgUbFuV1jFzPqvE'}, {'album_id': '5d0eh1FoU7tOYEnHLohjjv', 'album_name': 'Sita Ramam (Telugu) (Extended Version) [Original Motion Picture Soundtrack]', 'album_release_date': '2022-09-08', 'album_total_tracks': 10, 'album_spotify_url': 'https://open.spotify.com/track/0sd5MZPkgjHzTlrrZE4XDk'}, {'album_id': '5d0eh1FoU7tOYEnHLohjjv', 'album_name': 'Sita Ramam (Telugu) (Extended Version) [Original Motion Picture Soundtrack]', 'album_release_date': '2022-09-08', 'album_total_tracks': 10, 'album_spotify_url': 'https://open.spotify.com/track/63NdWczrPCYGWKY1RV4Zbh'}, {'album_id': '5d0eh1FoU7tOYEnHLohjjv', 'album_name': 'Sita Ramam (Telugu) (Extended Version) [Original Motion Picture Soundtrack]', 'album_release_date': '2022-09-08', 'album_total_tracks': 10, 'album_spotify_url': 'https://open.spotify.com/track/6DH51oJbucwELZLfTYAZkT'}, {'album_id': '5d0eh1FoU7tOYEnHLohjjv', 'album_name': 'Sita Ramam (Telugu) (Extended Version) [Original Motion Picture Soundtrack]', 'album_release_date': '2022-09-08', 'album_total_tracks': 10, 'album_spotify_url': 'https://open.spotify.com/track/54EJAhkEo4ERDUVQMoWdtb'}, {'album_id': '3OE7LZ7rSmnpDz0L5NaTJR', 'album_name': 'Sita Ramam (Hindi) [Original Motion Picture Soundtrack]', 'album_release_date': '2022-09-02', 'album_total_tracks': 10, 'album_spotify_url': 'https://open.spotify.com/track/04RL413v1BqfHMDNCmKBAI'}, {'album_id': '2OyJ5P81elIOSPFSj2gnkE', 'album_name': 'Godavari', 'album_release_date': '2013-01-15', 'album_total_tracks': 7, 'album_spotify_url': 'https://open.spotify.com/track/1qnB1JUsGwOK5VnZflixBB'}, {'album_id': '2OyJ5P81elIOSPFSj2gnkE', 'album_name': 'Godavari', 'album_release_date': '2013-01-15', 'album_total_tracks': 7, 'album_spotify_url': 'https://open.spotify.com/track/0OfaxrkK5wNf6Gotdph5Jz'}, {'album_id': '2OyJ5P81elIOSPFSj2gnkE', 'album_name': 'Godavari', 'album_release_date': '2013-01-15', 'album_total_tracks': 7, 'album_spotify_url': 'https://open.spotify.com/track/4MD9HLsY2JheBumbYjEbTV'}, {'album_id': '2OyJ5P81elIOSPFSj2gnkE', 'album_name': 'Godavari', 'album_release_date': '2013-01-15', 'album_total_tracks': 7, 'album_spotify_url': 'https://open.spotify.com/track/1UBM4j8bzMnQaKHDaairxW'}, {'album_id': '2OyJ5P81elIOSPFSj2gnkE', 'album_name': 'Godavari', 'album_release_date': '2013-01-15', 'album_total_tracks': 7, 'album_spotify_url': 'https://open.spotify.com/track/46IqUkQTOH7aEaZFUcpSON'}, {'album_id': '2OyJ5P81elIOSPFSj2gnkE', 'album_name': 'Godavari', 'album_release_date': '2013-01-15', 'album_total_tracks': 7, 'album_spotify_url': 'https://open.spotify.com/track/7l5fS4lbkdwzteVyE6s2IO'}, {'album_id': '2OyJ5P81elIOSPFSj2gnkE', 'album_name': 'Godavari', 'album_release_date': '2013-01-15', 'album_total_tracks': 7, 'album_spotify_url': 'https://open.spotify.com/track/16beX6njtdasRvgm86HEg6'}, {'album_id': '7qe9NgxK1B9zNTyZLUF5pG', 'album_name': 'Anand', 'album_release_date': '2004-07-09', 'album_total_tracks': 6, 'album_spotify_url': 'https://open.spotify.com/track/2g5t70UUP6nPpyZdyQQJz2'}, {'album_id': '7qe9NgxK1B9zNTyZLUF5pG', 'album_name': 'Anand', 'album_release_date': '2004-07-09', 'album_total_tracks': 6, 'album_spotify_url': 'https://open.spotify.com/track/7o6iBqzR1iIN8X2IpvLmVw'}, {'album_id': '7qe9NgxK1B9zNTyZLUF5pG', 'album_name': 'Anand', 'album_release_date': '2004-07-09', 'album_total_tracks': 6, 'album_spotify_url': 'https://open.spotify.com/track/4k6N1wRZ5Im7KmbINgBdO3'}, {'album_id': '7qe9NgxK1B9zNTyZLUF5pG', 'album_name': 'Anand', 'album_release_date': '2004-07-09', 'album_total_tracks': 6, 'album_spotify_url': 'https://open.spotify.com/track/76WzfVTkixrm5P6oupw4KY'}, {'album_id': '7qe9NgxK1B9zNTyZLUF5pG', 'album_name': 'Anand', 'album_release_date': '2004-07-09', 'album_total_tracks': 6, 'album_spotify_url': 'https://open.spotify.com/track/2zMR9S3JRW0fplrVCAWIDf'}, {'album_id': '7qe9NgxK1B9zNTyZLUF5pG', 'album_name': 'Anand', 'album_release_date': '2004-07-09', 'album_total_tracks': 6, 'album_spotify_url': 'https://open.spotify.com/track/6U8Gvg0lqTZzrSOgIZcf0Z'}, {'album_id': '5pZ7o500CAKbB4ciJVBNyl', 'album_name': 'Santhosham', 'album_release_date': '2002-05-09', 'album_total_tracks': 8, 'album_spotify_url': 'https://open.spotify.com/track/1DpG1xxz90gjxjmbuNc4Z7'}, {'album_id': '5pZ7o500CAKbB4ciJVBNyl', 'album_name': 'Santhosham', 'album_release_date': '2002-05-09', 'album_total_tracks': 8, 'album_spotify_url': 'https://open.spotify.com/track/6kFb1tl29cc8sa9Sr178af'}, {'album_id': '5pZ7o500CAKbB4ciJVBNyl', 'album_name': 'Santhosham', 'album_release_date': '2002-05-09', 'album_total_tracks': 8, 'album_spotify_url': 'https://open.spotify.com/track/0olcG4suN6NWmimWuuvOMU'}, {'album_id': '5pZ7o500CAKbB4ciJVBNyl', 'album_name': 'Santhosham', 'album_release_date': '2002-05-09', 'album_total_tracks': 8, 'album_spotify_url': 'https://open.spotify.com/track/4Y3HG8mmJYpHN05X7SWWHI'}, {'album_id': '5pZ7o500CAKbB4ciJVBNyl', 'album_name': 'Santhosham', 'album_release_date': '2002-05-09', 'album_total_tracks': 8, 'album_spotify_url': 'https://open.spotify.com/track/4mIOdOh49kfRSZBwvylulK'}, {'album_id': '5pZ7o500CAKbB4ciJVBNyl', 'album_name': 'Santhosham', 'album_release_date': '2002-05-09', 'album_total_tracks': 8, 'album_spotify_url': 'https://open.spotify.com/track/0xbSPPjXQkxUZSkj7n7C34'}, {'album_id': '5pZ7o500CAKbB4ciJVBNyl', 'album_name': 'Santhosham', 'album_release_date': '2002-05-09', 'album_total_tracks': 8, 'album_spotify_url': 'https://open.spotify.com/track/4A6j0Du0IrhL5F8smYVMTq'}, {'album_id': '5pZ7o500CAKbB4ciJVBNyl', 'album_name': 'Santhosham', 'album_release_date': '2002-05-09', 'album_total_tracks': 8, 'album_spotify_url': 'https://open.spotify.com/track/23TzyhGzuYdpnJeuiXJBtN'}, {'album_id': '5I3dEH9cXdYmo8MVIdOkxO', 'album_name': 'Nuvvostanante Nenoddantana', 'album_release_date': '2005-01-14', 'album_total_tracks': 7, 'album_spotify_url': 'https://open.spotify.com/track/1ifMH14KizpUxIdRVyPsSZ'}, {'album_id': '5I3dEH9cXdYmo8MVIdOkxO', 'album_name': 'Nuvvostanante Nenoddantana', 'album_release_date': '2005-01-14', 'album_total_tracks': 7, 'album_spotify_url': 'https://open.spotify.com/track/4EztIh7yvgYs9YLCvxT8ku'}, {'album_id': '5I3dEH9cXdYmo8MVIdOkxO', 'album_name': 'Nuvvostanante Nenoddantana', 'album_release_date': '2005-01-14', 'album_total_tracks': 7, 'album_spotify_url': 'https://open.spotify.com/track/69PuGOoNWxd2hM0tsrCa2O'}, {'album_id': '5I3dEH9cXdYmo8MVIdOkxO', 'album_name': 'Nuvvostanante Nenoddantana', 'album_release_date': '2005-01-14', 'album_total_tracks': 7, 'album_spotify_url': 'https://open.spotify.com/track/4b4xkbpRpA8jHbP8GVLYWR'}, {'album_id': '5I3dEH9cXdYmo8MVIdOkxO', 'album_name': 'Nuvvostanante Nenoddantana', 'album_release_date': '2005-01-14', 'album_total_tracks': 7, 'album_spotify_url': 'https://open.spotify.com/track/3Gmq2pQZNo5TqrobE10WgA'}, {'album_id': '5I3dEH9cXdYmo8MVIdOkxO', 'album_name': 'Nuvvostanante Nenoddantana', 'album_release_date': '2005-01-14', 'album_total_tracks': 7, 'album_spotify_url': 'https://open.spotify.com/track/6OJemp4sHmpogO2ieTATsq'}, {'album_id': '5I3dEH9cXdYmo8MVIdOkxO', 'album_name': 'Nuvvostanante Nenoddantana', 'album_release_date': '2005-01-14', 'album_total_tracks': 7, 'album_spotify_url': 'https://open.spotify.com/track/4FexaCwCrxQ9OErHZiLlWh'}, {'album_id': '67FATbnVWtXgD9TF6OGb3P', 'album_name': 'Most Eligible Bachelor', 'album_release_date': '2020-03-02', 'album_total_tracks': 5, 'album_spotify_url': 'https://open.spotify.com/track/28GsFcWboBzq0kVMXl0cDL'}, {'album_id': '67FATbnVWtXgD9TF6OGb3P', 'album_name': 'Most Eligible Bachelor', 'album_release_date': '2020-03-02', 'album_total_tracks': 5, 'album_spotify_url': 'https://open.spotify.com/track/0eBqUmGdSPM922MHW1wGem'}, {'album_id': '67FATbnVWtXgD9TF6OGb3P', 'album_name': 'Most Eligible Bachelor', 'album_release_date': '2020-03-02', 'album_total_tracks': 5, 'album_spotify_url': 'https://open.spotify.com/track/15aagpaC5XENZJUYW954Ot'}, {'album_id': '67FATbnVWtXgD9TF6OGb3P', 'album_name': 'Most Eligible Bachelor', 'album_release_date': '2020-03-02', 'album_total_tracks': 5, 'album_spotify_url': 'https://open.spotify.com/track/0pCXbJ3lbtinCZnwg1CYDC'}, {'album_id': '67FATbnVWtXgD9TF6OGb3P', 'album_name': 'Most Eligible Bachelor', 'album_release_date': '2020-03-02', 'album_total_tracks': 5, 'album_spotify_url': 'https://open.spotify.com/track/0WpVe4KIQpuCsAdzG3FubQ'}, {'album_id': '7hGQiJXERTnhQbW5cyo2bA', 'album_name': 'Chogada (From "Loveyatri")', 'album_release_date': '2018-08-14', 'album_total_tracks': 1, 'album_spotify_url': 'https://open.spotify.com/track/4ymPEyiXabTe1NO8q8EFxG'}, {'album_id': '0jhDiAfzNalPhA0YmgI4df', 'album_name': 'Mitron (Original Motion Picture Soundtrack)', 'album_release_date': '2018-08-30', 'album_total_tracks': 7, 'album_spotify_url': 'https://open.spotify.com/track/5HJvDTnAaDWqhsE841I1QR'}, {'album_id': '0UuTH5r9tyFJ2tqnvc1wWm', 'album_name': 'M.S.Dhoni - The Untold Story', 'album_release_date': '2016-09-17', 'album_total_tracks': 7, 'album_spotify_url': 'https://open.spotify.com/track/0pWcUM0z72DhTW7j0fa0QM'}, {'album_id': '0UuTH5r9tyFJ2tqnvc1wWm', 'album_name': 'M.S.Dhoni - The Untold Story', 'album_release_date': '2016-09-17', 'album_total_tracks': 7, 'album_spotify_url': 'https://open.spotify.com/track/4jk4CaqBMBbMZhf3PuR1ai'}, {'album_id': '0UuTH5r9tyFJ2tqnvc1wWm', 'album_name': 'M.S.Dhoni - The Untold Story', 'album_release_date': '2016-09-17', 'album_total_tracks': 7, 'album_spotify_url': 'https://open.spotify.com/track/35RWttZt8zGGzT0mWtlXpn'}, {'album_id': '0UuTH5r9tyFJ2tqnvc1wWm', 'album_name': 'M.S.Dhoni - The Untold Story', 'album_release_date': '2016-09-17', 'album_total_tracks': 7, 'album_spotify_url': 'https://open.spotify.com/track/5T2ZZiBMDGh3TZDUbxg4rV'}, {'album_id': '3piLZD41AqCHMXg2PDeRhj', 'album_name': 'Kaun Tujhe (Armaan Malik Version)', 'album_release_date': '2017-01-11', 'album_total_tracks': 1, 'album_spotify_url': 'https://open.spotify.com/track/5fjIpQa7O7ttgx64TN9lZR'}, {'album_id': '0UuTH5r9tyFJ2tqnvc1wWm', 'album_name': 'M.S.Dhoni - The Untold Story', 'album_release_date': '2016-09-17', 'album_total_tracks': 7, 'album_spotify_url': 'https://open.spotify.com/track/1YzWe6GO09gZRoZvGRSfmZ'}, {'album_id': '0UuTH5r9tyFJ2tqnvc1wWm', 'album_name': 'M.S.Dhoni - The Untold Story', 'album_release_date': '2016-09-17', 'album_total_tracks': 7, 'album_spotify_url': 'https://open.spotify.com/track/59RXttbK7hgRfnMTMVg2xm'}, {'album_id': '0714Rv0Cn3EcqVUZI2JwuM', 'album_name': 'Har Gully Mein Dhoni Hai', 'album_release_date': '2016-09-21', 'album_total_tracks': 1, 'album_spotify_url': 'https://open.spotify.com/track/416JrHCQSGotp7jSNoY6tp'}, {'album_id': '0UuTH5r9tyFJ2tqnvc1wWm', 'album_name': 'M.S.Dhoni - The Untold Story', 'album_release_date': '2016-09-17', 'album_total_tracks': 7, 'album_spotify_url': 'https://open.spotify.com/track/7gP2l6qxpeN8t71MhXO8rd'}]

# Extracting Artists

In [13]:
artists = []

for row in results['items']:
    for key,value in row.items():
        if key == 'item':
            for artist in value['artists']:
                artist_dict = {
                    'artist_id': artist['id'],
                    'artist_name': artist['name'],
                    'external_url': artist['href']
                }
                artists.append(artist_dict)
print(artists)

[{'artist_id': '5as8A4G47Ohu9NSWs3Je8U', 'artist_name': 'Asha Bhosle', 'external_url': 'https://api.spotify.com/v1/artists/5as8A4G47Ohu9NSWs3Je8U'}, {'artist_id': '579pH2PjdCVSkAyFBv2Z8g', 'artist_name': 'K M Radhakrishnan', 'external_url': 'https://api.spotify.com/v1/artists/579pH2PjdCVSkAyFBv2Z8g'}, {'artist_id': '0BDs2eNYNZvlMnnlijsfoL', 'artist_name': 'Jessi Gift', 'external_url': 'https://api.spotify.com/v1/artists/0BDs2eNYNZvlMnnlijsfoL'}, {'artist_id': '3QL2xVnI7n5Fng1l4e56AP', 'artist_name': 'Mamta Mohandas', 'external_url': 'https://api.spotify.com/v1/artists/3QL2xVnI7n5Fng1l4e56AP'}, {'artist_id': '1QvyquqkuuwUzdszyoKIy4', 'artist_name': 'Haricharan', 'external_url': 'https://api.spotify.com/v1/artists/1QvyquqkuuwUzdszyoKIy4'}, {'artist_id': '2JEjaa7hWhE1BbL3OcoeFR', 'artist_name': 'Sujatha', 'external_url': 'https://api.spotify.com/v1/artists/2JEjaa7hWhE1BbL3OcoeFR'}, {'artist_id': '4zCH9qm4R2DADamUHMCa6O', 'artist_name': 'Anirudh Ravichander', 'external_url': 'https://api.spotify.com/v1/artists/4zCH9qm4R2DADamUHMCa6O'}, {'artist_id': '3ocTwOjekTkFdD695eKuQr', 'artist_name': 'Justin Prabhakaran', 'external_url': 'https://api.spotify.com/v1/artists/3ocTwOjekTkFdD695eKuQr'}, {'artist_id': '2yvOLf1gt6m9qPgzzqpxQx', 'artist_name': 'Krishna Kanth', 'external_url': 'https://api.spotify.com/v1/artists/2yvOLf1gt6m9qPgzzqpxQx'}, {'artist_id': '7qjJw7ZM2ekDSahLXPjIlN', 'artist_name': 'Sid Sriram', 'external_url': 'https://api.spotify.com/v1/artists/7qjJw7ZM2ekDSahLXPjIlN'}, {'artist_id': '3ocTwOjekTkFdD695eKuQr', 'artist_name': 'Justin Prabhakaran', 'external_url': 'https://api.spotify.com/v1/artists/3ocTwOjekTkFdD695eKuQr'}, {'artist_id': '2yvOLf1gt6m9qPgzzqpxQx', 'artist_name': 'Krishna Kanth', 'external_url': 'https://api.spotify.com/v1/artists/2yvOLf1gt6m9qPgzzqpxQx'}, {'artist_id': '6AiX12wXdXFoGJ2vk8zBjy', 'artist_name': 'Yuvan Shankar Raja', 'external_url': 'https://api.spotify.com/v1/artists/6AiX12wXdXFoGJ2vk8zBjy'}, {'artist_id': '1lr0MlyZ8Q24eFtn7gcMmI', 'artist_name': 'Harini Ivaturi', 'external_url': 'https://api.spotify.com/v1/artists/1lr0MlyZ8Q24eFtn7gcMmI'}, {'artist_id': '3ocTwOjekTkFdD695eKuQr', 'artist_name': 'Justin Prabhakaran', 'external_url': 'https://api.spotify.com/v1/artists/3ocTwOjekTkFdD695eKuQr'}, {'artist_id': '2yvOLf1gt6m9qPgzzqpxQx', 'artist_name': 'Krishna Kanth', 'external_url': 'https://api.spotify.com/v1/artists/2yvOLf1gt6m9qPgzzqpxQx'}, {'artist_id': '6LWyVEIBnx7MoRBhQxu9om', 'artist_name': 'Anurag Kulkarni', 'external_url': 'https://api.spotify.com/v1/artists/6LWyVEIBnx7MoRBhQxu9om'}, {'artist_id': '0oOet2f43PA68X5RxKobEy', 'artist_name': 'Shreya Ghoshal', 'external_url': 'https://api.spotify.com/v1/artists/0oOet2f43PA68X5RxKobEy'}, {'artist_id': '3ocTwOjekTkFdD695eKuQr', 'artist_name': 'Justin Prabhakaran', 'external_url': 'https://api.spotify.com/v1/artists/3ocTwOjekTkFdD695eKuQr'}, {'artist_id': '2yvOLf1gt6m9qPgzzqpxQx', 'artist_name': 'Krishna Kanth', 'external_url': 'https://api.spotify.com/v1/artists/2yvOLf1gt6m9qPgzzqpxQx'}, {'artist_id': '5cPMKXyysDCkZr4ERLYbkq', 'artist_name': 'Sathya Yamini', 'external_url': 'https://api.spotify.com/v1/artists/5cPMKXyysDCkZr4ERLYbkq'}, {'artist_id': '3ocTwOjekTkFdD695eKuQr', 'artist_name': 'Justin Prabhakaran', 'external_url': 'https://api.spotify.com/v1/artists/3ocTwOjekTkFdD695eKuQr'}, {'artist_id': '0Mbxm07Hiahy2xSMtesff8', 'artist_name': 'Aishwarya Ravichandran', 'external_url': 'https://api.spotify.com/v1/artists/0Mbxm07Hiahy2xSMtesff8'}, {'artist_id': '3ocTwOjekTkFdD695eKuQr', 'artist_name': 'Justin Prabhakaran', 'external_url': 'https://api.spotify.com/v1/artists/3ocTwOjekTkFdD695eKuQr'}, {'artist_id': '3ocTwOjekTkFdD695eKuQr', 'artist_name': 'Justin Prabhakaran', 'external_url': 'https://api.spotify.com/v1/artists/3ocTwOjekTkFdD695eKuQr'}, {'artist_id': '4fEkbug6kZzzJ8eYX6Kbbp', 'artist_name': 'KK', 'external_url': 'https://api.spotify.com/v1/artists/4fEkbug6kZzzJ8eYX6Kbbp'}, {'artist_id': '70B80Lwx2sxti0M1Ng9e8K', 'artist_name': 'Udit Narayan', 'external_url': 'https://api.spotify.com/v1/artists/70B80Lwx2sxti0M1Ng9e8K'}, {'artist_id': '6WPmTGeeoymoVlXVtsCwz7', 'artist_name': 'Kavita Krishnamurthy', 'external_url': 'https://api.spotify.com/v1/artists/6WPmTGeeoymoVlXVtsCwz7'}, {'artist_id': '3K9qRRRqtuxgBRLxRCxpDl', 'artist_name': 'Srinivas', 'external_url': 'https://api.spotify.com/v1/artists/3K9qRRRqtuxgBRLxRCxpDl'}, {'artist_id': '41BeeC5hYqvtGkM79RYvN4', 'artist_name': 'Harini', 'external_url': 'https://api.spotify.com/v1/artists/41BeeC5hYqvtGkM79RYvN4'}, {'artist_id': '1HUZ6vfsSWpfLoxjgDavEB', 'artist_name': 'Devan Ekambaram', 'external_url': 'https://api.spotify.com/v1/artists/1HUZ6vfsSWpfLoxjgDavEB'}, {'artist_id': '1RMmK2dEtVEbhSV7qvSXJ1', 'artist_name': 'Kalpana Patowary', 'external_url': 'https://api.spotify.com/v1/artists/1RMmK2dEtVEbhSV7qvSXJ1'}, {'artist_id': '6rpx3XvLyeqyZFiNJwzjvM', 'artist_name': 'Samatha Fernander', 'external_url': 'https://api.spotify.com/v1/artists/6rpx3XvLyeqyZFiNJwzjvM'}, {'artist_id': '3zry1HzVn8WqSFHigzZ8bx', 'artist_name': 'Muralidar', 'external_url': 'https://api.spotify.com/v1/artists/3zry1HzVn8WqSFHigzZ8bx'}, {'artist_id': '3NzhVoa20crNtp1p4zE8um', 'artist_name': 'Mano', 'external_url': 'https://api.spotify.com/v1/artists/3NzhVoa20crNtp1p4zE8um'}, {'artist_id': '7N0SBLJFpCyQSsv4MfRJ5d', 'artist_name': 'Swarnalatha', 'external_url': 'https://api.spotify.com/v1/artists/7N0SBLJFpCyQSsv4MfRJ5d'}, {'artist_id': '50iBEPSw6kQ8GQkumXz7XZ', 'artist_name': 'Hesham Abdul Wahab', 'external_url': 'https://api.spotify.com/v1/artists/50iBEPSw6kQ8GQkumXz7XZ'}, {'artist_id': '50iBEPSw6kQ8GQkumXz7XZ', 'artist_name': 'Hesham Abdul Wahab', 'external_url': 'https://api.spotify.com/v1/artists/50iBEPSw6kQ8GQkumXz7XZ'}, {'artist_id': '7qjJw7ZM2ekDSahLXPjIlN', 'artist_name': 'Sid Sriram', 'external_url': 'https://api.spotify.com/v1/artists/7qjJw7ZM2ekDSahLXPjIlN'}, {'artist_id': '5UJ2sHO2ELrgW6aXeRLTQQ', 'artist_name': 'Chinmayi', 'external_url': 'https://api.spotify.com/v1/artists/5UJ2sHO2ELrgW6aXeRLTQQ'}, {'artist_id': '50iBEPSw6kQ8GQkumXz7XZ', 'artist_name': 'Hesham Abdul Wahab', 'external_url': 'https://api.spotify.com/v1/artists/50iBEPSw6kQ8GQkumXz7XZ'}, {'artist_id': '50iBEPSw6kQ8GQkumXz7XZ', 'artist_name': 'Hesham Abdul Wahab', 'external_url': 'https://api.spotify.com/v1/artists/50iBEPSw6kQ8GQkumXz7XZ'}, {'artist_id': '3fjEU4fb7YikO0zObLz159', 'artist_name': 'Divya S Menon', 'external_url': 'https://api.spotify.com/v1/artists/3fjEU4fb7YikO0zObLz159'}, {'artist_id': '50iBEPSw6kQ8GQkumXz7XZ', 'artist_name': 'Hesham Abdul Wahab', 'external_url': 'https://api.spotify.com/v1/artists/50iBEPSw6kQ8GQkumXz7XZ'}, {'artist_id': '1H4ZvA2yyK7wCmbvEUWvPn', 'artist_name': 'Rahul Sipligunj', 'external_url': 'https://api.spotify.com/v1/artists/1H4ZvA2yyK7wCmbvEUWvPn'}, {'artist_id': '3MoBedNBt9D9IRmhRJxV3L', 'artist_name': 'Saketh Komanduri', 'external_url': 'https://api.spotify.com/v1/artists/3MoBedNBt9D9IRmhRJxV3L'}, {'artist_id': '4A2XSc4OJjuPY4l6NjnrDj', 'artist_name': 'Ram Miriyala', 'external_url': 'https://api.spotify.com/v1/artists/4A2XSc4OJjuPY4l6NjnrDj'}, {'artist_id': '4A2XSc4OJjuPY4l6NjnrDj', 'artist_name': 'Ram Miriyala', 'external_url': 'https://api.spotify.com/v1/artists/4A2XSc4OJjuPY4l6NjnrDj'}, {'artist_id': '4wxBWsFkyA2K1BMBFj91qt', 'artist_name': 'Kasarla Shyam', 'external_url': 'https://api.spotify.com/v1/artists/4wxBWsFkyA2K1BMBFj91qt'}, {'artist_id': '4A2XSc4OJjuPY4l6NjnrDj', 'artist_name': 'Ram Miriyala', 'external_url': 'https://api.spotify.com/v1/artists/4A2XSc4OJjuPY4l6NjnrDj'}, {'artist_id': '4wxBWsFkyA2K1BMBFj91qt', 'artist_name': 'Kasarla Shyam', 'external_url': 'https://api.spotify.com/v1/artists/4wxBWsFkyA2K1BMBFj91qt'}, {'artist_id': '13M1OXRslYiaRoeaUx75uY', 'artist_name': 'Achu', 'external_url': 'https://api.spotify.com/v1/artists/13M1OXRslYiaRoeaUx75uY'}, {'artist_id': '2bfyLSCw72lQ5qoD8cdVBB', 'artist_name': 'Sreerama Chandra', 'external_url': 'https://api.spotify.com/v1/artists/2bfyLSCw72lQ5qoD8cdVBB'}, {'artist_id': '5qtGaQLgSlCzReVy1pn0gS', 'artist_name': 'Siddhu Jonnalagadda', 'external_url': 'https://api.spotify.com/v1/artists/5qtGaQLgSlCzReVy1pn0gS'}, {'artist_id': '3QoSfUFXgGywfwAC31leoK', 'artist_name': 'Ravi Anthony', 'external_url': 'https://api.spotify.com/v1/artists/3QoSfUFXgGywfwAC31leoK'}, {'artist_id': '2hNON05iexckgWGTpiOg9L', 'artist_name': 'Usha', 'external_url': 'https://api.spotify.com/v1/artists/2hNON05iexckgWGTpiOg9L'}, {'artist_id': '00hL0oJD4pWef0kPYIaSTy', 'artist_name': 'R. P. Patnaik', 'external_url': 'https://api.spotify.com/v1/artists/00hL0oJD4pWef0kPYIaSTy'}, {'artist_id': '2hNON05iexckgWGTpiOg9L', 'artist_name': 'Usha', 'external_url': 'https://api.spotify.com/v1/artists/2hNON05iexckgWGTpiOg9L'}, {'artist_id': '147FmQtrv7N2tKKZixcnG3', 'artist_name': 'Lenina', 'external_url': 'https://api.spotify.com/v1/artists/147FmQtrv7N2tKKZixcnG3'}, {'artist_id': '2hNON05iexckgWGTpiOg9L', 'artist_name': 'Usha', 'external_url': 'https://api.spotify.com/v1/artists/2hNON05iexckgWGTpiOg9L'}, {'artist_id': '00hL0oJD4pWef0kPYIaSTy', 'artist_name': 'R. P. Patnaik', 'external_url': 'https://api.spotify.com/v1/artists/00hL0oJD4pWef0kPYIaSTy'}, {'artist_id': '00hL0oJD4pWef0kPYIaSTy', 'artist_name': 'R. P. Patnaik', 'external_url': 'https://api.spotify.com/v1/artists/00hL0oJD4pWef0kPYIaSTy'}, {'artist_id': '1W9j3itOGw4WqyuZuErSqF', 'artist_name': 'Kousalya', 'external_url': 'https://api.spotify.com/v1/artists/1W9j3itOGw4WqyuZuErSqF'}, {'artist_id': '2hNON05iexckgWGTpiOg9L', 'artist_name': 'Usha', 'external_url': 'https://api.spotify.com/v1/artists/2hNON05iexckgWGTpiOg9L'}, {'artist_id': '2ae6PxICSOZHvjqiCcgon8', 'artist_name': 'S. P. Balasubrahmanyam', 'external_url': 'https://api.spotify.com/v1/artists/2ae6PxICSOZHvjqiCcgon8'}, {'artist_id': '0rL4uL3xfYOt2p7NHhS8qr', 'artist_name': 'Vishal Chandrashekhar', 'external_url': 'https://api.spotify.com/v1/artists/0rL4uL3xfYOt2p7NHhS8qr'}, {'artist_id': '1BIAyVQxDuYrMqZ8H1Faja', 'artist_name': 'S.P. Charan', 'external_url': 'https://api.spotify.com/v1/artists/1BIAyVQxDuYrMqZ8H1Faja'}, {'artist_id': '4svvMm4TQnkphZJfhLCzzv', 'artist_name': 'Ramya Behara', 'external_url': 'https://api.spotify.com/v1/artists/4svvMm4TQnkphZJfhLCzzv'}, {'artist_id': '5wE0KHIPasAq9oKW3PkDpq', 'artist_name': 'Anantha Sriram', 'external_url': 'https://api.spotify.com/v1/artists/5wE0KHIPasAq9oKW3PkDpq'}, {'artist_id': '0rL4uL3xfYOt2p7NHhS8qr', 'artist_name': 'Vishal Chandrashekhar', 'external_url': 'https://api.spotify.com/v1/artists/0rL4uL3xfYOt2p7NHhS8qr'}, {'artist_id': '6LWyVEIBnx7MoRBhQxu9om', 'artist_name': 'Anurag Kulkarni', 'external_url': 'https://api.spotify.com/v1/artists/6LWyVEIBnx7MoRBhQxu9om'}, {'artist_id': '6KjiNHnbm1CNrIN0z7wJtO', 'artist_name': 'Sinduri Vishal', 'external_url': 'https://api.spotify.com/v1/artists/6KjiNHnbm1CNrIN0z7wJtO'}, {'artist_id': '6AgipdEVghvFGPxilhdrBO', 'artist_name': 'Sirivennela Seetharama Sastry', 'external_url': 'https://api.spotify.com/v1/artists/6AgipdEVghvFGPxilhdrBO'}, {'artist_id': '0rL4uL3xfYOt2p7NHhS8qr', 'artist_name': 'Vishal Chandrashekhar', 'external_url': 'https://api.spotify.com/v1/artists/0rL4uL3xfYOt2p7NHhS8qr'}, {'artist_id': '2pVurQy6iuWWx707gilSdX', 'artist_name': 'Yazin Nizar', 'external_url': 'https://api.spotify.com/v1/artists/2pVurQy6iuWWx707gilSdX'}, {'artist_id': '2yvOLf1gt6m9qPgzzqpxQx', 'artist_name': 'Krishna Kanth', 'external_url': 'https://api.spotify.com/v1/artists/2yvOLf1gt6m9qPgzzqpxQx'}, {'artist_id': '0rL4uL3xfYOt2p7NHhS8qr', 'artist_name': 'Vishal Chandrashekhar', 'external_url': 'https://api.spotify.com/v1/artists/0rL4uL3xfYOt2p7NHhS8qr'}, {'artist_id': '0nMjhemqRwrboQGcs92fh2', 'artist_name': 'Kapil Kapilan', 'external_url': 'https://api.spotify.com/v1/artists/0nMjhemqRwrboQGcs92fh2'}, {'artist_id': '5UJ2sHO2ELrgW6aXeRLTQQ', 'artist_name': 'Chinmayi', 'external_url': 'https://api.spotify.com/v1/artists/5UJ2sHO2ELrgW6aXeRLTQQ'}, {'artist_id': '2yvOLf1gt6m9qPgzzqpxQx', 'artist_name': 'Krishna Kanth', 'external_url': 'https://api.spotify.com/v1/artists/2yvOLf1gt6m9qPgzzqpxQx'}, {'artist_id': '0rL4uL3xfYOt2p7NHhS8qr', 'artist_name': 'Vishal Chandrashekhar', 'external_url': 'https://api.spotify.com/v1/artists/0rL4uL3xfYOt2p7NHhS8qr'}, {'artist_id': '74S8YRi4XQ5yf9ToSzuY80', 'artist_name': 'Sunitha', 'external_url': 'https://api.spotify.com/v1/artists/74S8YRi4XQ5yf9ToSzuY80'}, {'artist_id': '0rL4uL3xfYOt2p7NHhS8qr', 'artist_name': 'Vishal Chandrashekhar', 'external_url': 'https://api.spotify.com/v1/artists/0rL4uL3xfYOt2p7NHhS8qr'}, {'artist_id': '2NoJ7NuNs9nyj8Thoh1kbu', 'artist_name': 'Hariharan', 'external_url': 'https://api.spotify.com/v1/artists/2NoJ7NuNs9nyj8Thoh1kbu'}, {'artist_id': '2IUtwMti1OiT3lkW6RubgH', 'artist_name': 'K. S. Chithra', 'external_url': 'https://api.spotify.com/v1/artists/2IUtwMti1OiT3lkW6RubgH'}, {'artist_id': '6KjiNHnbm1CNrIN0z7wJtO', 'artist_name': 'Sinduri Vishal', 'external_url': 'https://api.spotify.com/v1/artists/6KjiNHnbm1CNrIN0z7wJtO'}, {'artist_id': '0rL4uL3xfYOt2p7NHhS8qr', 'artist_name': 'Vishal Chandrashekhar', 'external_url': 'https://api.spotify.com/v1/artists/0rL4uL3xfYOt2p7NHhS8qr'}, {'artist_id': '2pVurQy6iuWWx707gilSdX', 'artist_name': 'Yazin Nizar', 'external_url': 'https://api.spotify.com/v1/artists/2pVurQy6iuWWx707gilSdX'}, {'artist_id': '23tDn4nvBiCQroeeCwwCWT', 'artist_name': 'Varun Grover', 'external_url': 'https://api.spotify.com/v1/artists/23tDn4nvBiCQroeeCwwCWT'}, {'artist_id': '2ae6PxICSOZHvjqiCcgon8', 'artist_name': 'S. P. Balasubrahmanyam', 'external_url': 'https://api.spotify.com/v1/artists/2ae6PxICSOZHvjqiCcgon8'}, {'artist_id': '0mV4UQ0gHg59AAUtg968pX', 'artist_name': 'Unnikrishnan', 'external_url': 'https://api.spotify.com/v1/artists/0mV4UQ0gHg59AAUtg968pX'}, {'artist_id': '2IUtwMti1OiT3lkW6RubgH', 'artist_name': 'K. S. Chithra', 'external_url': 'https://api.spotify.com/v1/artists/2IUtwMti1OiT3lkW6RubgH'}, {'artist_id': '0oOet2f43PA68X5RxKobEy', 'artist_name': 'Shreya Ghoshal', 'external_url': 'https://api.spotify.com/v1/artists/0oOet2f43PA68X5RxKobEy'}, {'artist_id': '1SJOL9HJ08YOn92lFcYf8a', 'artist_name': 'Shankar Mahadevan', 'external_url': 'https://api.spotify.com/v1/artists/1SJOL9HJ08YOn92lFcYf8a'}, {'artist_id': '2IUtwMti1OiT3lkW6RubgH', 'artist_name': 'K. S. Chithra', 'external_url': 'https://api.spotify.com/v1/artists/2IUtwMti1OiT3lkW6RubgH'}, {'artist_id': '72AhOfYH44654ISqbuwdEZ', 'artist_name': 'Suneetha', 'external_url': 'https://api.spotify.com/v1/artists/72AhOfYH44654ISqbuwdEZ'}, {'artist_id': '2Ah48tA0TPqph0m9snNNxM', 'artist_name': 'Gayathri', 'external_url': 'https://api.spotify.com/v1/artists/2Ah48tA0TPqph0m9snNNxM'}, {'artist_id': '2Ah48tA0TPqph0m9snNNxM', 'artist_name': 'Gayathri', 'external_url': 'https://api.spotify.com/v1/artists/2Ah48tA0TPqph0m9snNNxM'}, {'artist_id': '2NoJ7NuNs9nyj8Thoh1kbu', 'artist_name': 'Hariharan', 'external_url': 'https://api.spotify.com/v1/artists/2NoJ7NuNs9nyj8Thoh1kbu'}, {'artist_id': '2IUtwMti1OiT3lkW6RubgH', 'artist_name': 'K. S. Chithra', 'external_url': 'https://api.spotify.com/v1/artists/2IUtwMti1OiT3lkW6RubgH'}, {'artist_id': '0oOet2f43PA68X5RxKobEy', 'artist_name': 'Shreya Ghoshal', 'external_url': 'https://api.spotify.com/v1/artists/0oOet2f43PA68X5RxKobEy'}, {'artist_id': '0oOet2f43PA68X5RxKobEy', 'artist_name': 'Shreya Ghoshal', 'external_url': 'https://api.spotify.com/v1/artists/0oOet2f43PA68X5RxKobEy'}, {'artist_id': '579pH2PjdCVSkAyFBv2Z8g', 'artist_name': 'K M Radhakrishnan', 'external_url': 'https://api.spotify.com/v1/artists/579pH2PjdCVSkAyFBv2Z8g'}, {'artist_id': '2L16nDKTxhFGaDriR2AHTB', 'artist_name': 'Lucky Ali', 'external_url': 'https://api.spotify.com/v1/artists/2L16nDKTxhFGaDriR2AHTB'}, {'artist_id': '0oOet2f43PA68X5RxKobEy', 'artist_name': 'Shreya Ghoshal', 'external_url': 'https://api.spotify.com/v1/artists/0oOet2f43PA68X5RxKobEy'}, {'artist_id': '2NoJ7NuNs9nyj8Thoh1kbu', 'artist_name': 'Hariharan', 'external_url': 'https://api.spotify.com/v1/artists/2NoJ7NuNs9nyj8Thoh1kbu'}, {'artist_id': '2IUtwMti1OiT3lkW6RubgH', 'artist_name': 'K. S. Chithra', 'external_url': 'https://api.spotify.com/v1/artists/2IUtwMti1OiT3lkW6RubgH'}, {'artist_id': '6aQ5LDX0WlnyDLI8TGU0wK', 'artist_name': 'Rajesh', 'external_url': 'https://api.spotify.com/v1/artists/6aQ5LDX0WlnyDLI8TGU0wK'}, {'artist_id': '2hNON05iexckgWGTpiOg9L', 'artist_name': 'Usha', 'external_url': 'https://api.spotify.com/v1/artists/2hNON05iexckgWGTpiOg9L'}, {'artist_id': '1SJOL9HJ08YOn92lFcYf8a', 'artist_name': 'Shankar Mahadevan', 'external_url': 'https://api.spotify.com/v1/artists/1SJOL9HJ08YOn92lFcYf8a'}, {'artist_id': '6aQ5LDX0WlnyDLI8TGU0wK', 'artist_name': 'Rajesh', 'external_url': 'https://api.spotify.com/v1/artists/6aQ5LDX0WlnyDLI8TGU0wK'}, {'artist_id': '4fEkbug6kZzzJ8eYX6Kbbp', 'artist_name': 'KK', 'external_url': 'https://api.spotify.com/v1/artists/4fEkbug6kZzzJ8eYX6Kbbp'}, {'artist_id': '2hNON05iexckgWGTpiOg9L', 'artist_name': 'Usha', 'external_url': 'https://api.spotify.com/v1/artists/2hNON05iexckgWGTpiOg9L'}, {'artist_id': '2hNON05iexckgWGTpiOg9L', 'artist_name': 'Usha', 'external_url': 'https://api.spotify.com/v1/artists/2hNON05iexckgWGTpiOg9L'}, {'artist_id': '3NzhVoa20crNtp1p4zE8um', 'artist_name': 'Mano', 'external_url': 'https://api.spotify.com/v1/artists/3NzhVoa20crNtp1p4zE8um'}, {'artist_id': '37LelbJh9kdExIMyaPBNS0', 'artist_name': 'Bhargavi', 'external_url': 'https://api.spotify.com/v1/artists/37LelbJh9kdExIMyaPBNS0'}, {'artist_id': '6leWXPFiNHLxf5IAjsD8P4', 'artist_name': 'Vishwa Vemuri', 'external_url': 'https://api.spotify.com/v1/artists/6leWXPFiNHLxf5IAjsD8P4'}, {'artist_id': '00hL0oJD4pWef0kPYIaSTy', 'artist_name': 'R. P. Patnaik', 'external_url': 'https://api.spotify.com/v1/artists/00hL0oJD4pWef0kPYIaSTy'}, {'artist_id': '4fEkbug6kZzzJ8eYX6Kbbp', 'artist_name': 'KK', 'external_url': 'https://api.spotify.com/v1/artists/4fEkbug6kZzzJ8eYX6Kbbp'}, {'artist_id': '2hNON05iexckgWGTpiOg9L', 'artist_name': 'Usha', 'external_url': 'https://api.spotify.com/v1/artists/2hNON05iexckgWGTpiOg9L'}, {'artist_id': '0LSPREIgGMZXCuKVel7LVD', 'artist_name': 'Karthik', 'external_url': 'https://api.spotify.com/v1/artists/0LSPREIgGMZXCuKVel7LVD'}, {'artist_id': '0WpkyIAATl5W540KCSEUwX', 'artist_name': 'Sumangaly', 'external_url': 'https://api.spotify.com/v1/artists/0WpkyIAATl5W540KCSEUwX'}, {'artist_id': '0PykiHCcDsMPRV7s67qZ1B', 'artist_name': 'Tippu', 'external_url': 'https://api.spotify.com/v1/artists/0PykiHCcDsMPRV7s67qZ1B'}, {'artist_id': '2ae6PxICSOZHvjqiCcgon8', 'artist_name': 'S. P. Balasubrahmanyam', 'external_url': 'https://api.spotify.com/v1/artists/2ae6PxICSOZHvjqiCcgon8'}, {'artist_id': '1SJOL9HJ08YOn92lFcYf8a', 'artist_name': 'Shankar Mahadevan', 'external_url': 'https://api.spotify.com/v1/artists/1SJOL9HJ08YOn92lFcYf8a'}, {'artist_id': '40Ce6P4AGMq3NXCDXVSZaa', 'artist_name': 'Mallikarjun', 'external_url': 'https://api.spotify.com/v1/artists/40Ce6P4AGMq3NXCDXVSZaa'}, {'artist_id': '6CWBs7ul78QwnBrcOCwhf5', 'artist_name': 'Sagar', 'external_url': 'https://api.spotify.com/v1/artists/6CWBs7ul78QwnBrcOCwhf5'}, {'artist_id': '6CWBs7ul78QwnBrcOCwhf5', 'artist_name': 'Sagar', 'external_url': 'https://api.spotify.com/v1/artists/6CWBs7ul78QwnBrcOCwhf5'}, {'artist_id': '3cowxATurZfjWsJC4uEHsl', 'artist_name': 'Jassie Gift', 'external_url': 'https://api.spotify.com/v1/artists/3cowxATurZfjWsJC4uEHsl'}, {'artist_id': '1RMmK2dEtVEbhSV7qvSXJ1', 'artist_name': 'Kalpana Patowary', 'external_url': 'https://api.spotify.com/v1/artists/1RMmK2dEtVEbhSV7qvSXJ1'}, {'artist_id': '7qjJw7ZM2ekDSahLXPjIlN', 'artist_name': 'Sid Sriram', 'external_url': 'https://api.spotify.com/v1/artists/7qjJw7ZM2ekDSahLXPjIlN'}, {'artist_id': '4IKVDbCSBTxBeAsMKjAuTs', 'artist_name': 'Armaan Malik', 'external_url': 'https://api.spotify.com/v1/artists/4IKVDbCSBTxBeAsMKjAuTs'}, {'artist_id': '2qE6XvN9lbEFGFfQOREsr0', 'artist_name': 'Haniya Nafisa', 'external_url': 'https://api.spotify.com/v1/artists/2qE6XvN9lbEFGFfQOREsr0'}, {'artist_id': '4xlqU0G9EloUPHL1qlmWY6', 'artist_name': 'Gopi Sundar', 'external_url': 'https://api.spotify.

# Extracting Songs

In [14]:
song_list = []

for row in results['items']:
    song_id = row['item']['id']
    song_name = row['item']['name']
    song_duration = row['item']['duration_ms']
    song_url = row['item']['external_urls']['spotify']
    song_added_at = row['added_at']
    album_id = row['item']['album']['id']
    artist_id = row['item']['artists'][0]['id']

    song_dict = {
        'song_id': song_id,
        'song_name': song_name,
        'song_duration': song_duration,
        'song_url': song_url,
        'song_added_at': song_added_at,
        'album_id': album_id,
        'artist_id': artist_id
    }
    song_list.append(song_dict)

print(song_list)

[{'song_id': '32faUN4IsCs1wk1ljIQr9C', 'song_name': 'Naalo Oohalaku', 'song_duration': 273776, 'song_url': 'https://open.spotify.com/track/32faUN4IsCs1wk1ljIQr9C', 'song_added_at': '2024-08-18T16:09:43Z', 'album_id': '2eASY2UZa4O8pdXvK9SNgC', 'artist_id': '5as8A4G47Ohu9NSWs3Je8U'}, {'song_id': '4yDzLrYRH1vMSI1qjR8ymb', 'song_name': 'Sakkubayiney', 'song_duration': 274454, 'song_url': 'https://open.spotify.com/track/4yDzLrYRH1vMSI1qjR8ymb', 'song_added_at': '2024-08-18T16:09:46Z', 'album_id': '2eASY2UZa4O8pdXvK9SNgC', 'artist_id': '0BDs2eNYNZvlMnnlijsfoL'}, {'song_id': '1DPRAIq9V0r2UPw4xA1iFf', 'song_name': 'Mukku Pye Muddu', 'song_duration': 278864, 'song_url': 'https://open.spotify.com/track/1DPRAIq9V0r2UPw4xA1iFf', 'song_added_at': '2024-08-18T16:09:50Z', 'album_id': '2eASY2UZa4O8pdXvK9SNgC', 'artist_id': '1QvyquqkuuwUzdszyoKIy4'}, {'song_id': '5C8b6OQlsIOtpbf6DCBkKk', 'song_name': 'Sanchari', 'song_duration': 268000, 'song_url': 'https://open.spotify.com/track/5C8b6OQlsIOtpbf6DCBkKk', 'song_added_at': '2024-08-18T16:10:00Z', 'album_id': '0oqXFsTVJInCqJJJAn7wel', 'artist_id': '4zCH9qm4R2DADamUHMCa6O'}, {'song_id': '56dpwomaj1YnKZ0L4b33hN', 'song_name': 'Nagumomu Thaarale', 'song_duration': 294115, 'song_url': 'https://open.spotify.com/track/56dpwomaj1YnKZ0L4b33hN', 'song_added_at': '2024-08-18T16:10:04Z', 'album_id': '0oqXFsTVJInCqJJJAn7wel', 'artist_id': '7qjJw7ZM2ekDSahLXPjIlN'}, {'song_id': '77feKtBcyhRv4SE2u6dd9R', 'song_name': 'Ee Raathale', 'song_duration': 232762, 'song_url': 'https://open.spotify.com/track/77feKtBcyhRv4SE2u6dd9R', 'song_added_at': '2024-08-18T16:10:10Z', 'album_id': '0oqXFsTVJInCqJJJAn7wel', 'artist_id': '6AiX12wXdXFoGJ2vk8zBjy'}, {'song_id': '7uo3wgB8We99kdcJpKDiq9', 'song_name': 'Ninnele', 'song_duration': 240070, 'song_url': 'https://open.spotify.com/track/7uo3wgB8We99kdcJpKDiq9', 'song_added_at': '2024-08-18T16:10:14Z', 'album_id': '0oqXFsTVJInCqJJJAn7wel', 'artist_id': '6LWyVEIBnx7MoRBhQxu9om'}, {'song_id': '4oV0B47QAl5k3efL3K4Sih', 'song_name': 'Krishna Krishna', 'song_duration': 107101, 'song_url': 'https://open.spotify.com/track/4oV0B47QAl5k3efL3K4Sih', 'song_added_at': '2024-08-18T16:10:18Z', 'album_id': '0oqXFsTVJInCqJJJAn7wel', 'artist_id': '5cPMKXyysDCkZr4ERLYbkq'}, {'song_id': '6GMGQ7BkieCY0X0MpiDOC7', 'song_name': 'Sundhara Vadhana', 'song_duration': 73386, 'song_url': 'https://open.spotify.com/track/6GMGQ7BkieCY0X0MpiDOC7', 'song_added_at': '2024-08-18T16:10:22Z', 'album_id': '0oqXFsTVJInCqJJJAn7wel', 'artist_id': '0Mbxm07Hiahy2xSMtesff8'}, {'song_id': '6e9k0zPtJfqJIseybAK2G0', 'song_name': 'Sei Un Angelo', 'song_duration': 54251, 'song_url': 'https://open.spotify.com/track/6e9k0zPtJfqJIseybAK2G0', 'song_added_at': '2024-08-18T16:10:26Z', 'album_id': '0oqXFsTVJInCqJJJAn7wel', 'artist_id': '3ocTwOjekTkFdD695eKuQr'}, {'song_id': '1ha2Dvv2vVyIbQUBCtbKvQ', 'song_name': 'Ye Mera Jaha', 'song_duration': 312781, 'song_url': 'https://open.spotify.com/track/1ha2Dvv2vVyIbQUBCtbKvQ', 'song_added_at': '2024-08-18T16:10:50Z', 'album_id': '37evPVtdfVL0X4Sji9tQdu', 'artist_id': '4fEkbug6kZzzJ8eYX6Kbbp'}, {'song_id': '2YZZFwARteC3gM1aEgHHMr', 'song_name': 'Ammaye', 'song_duration': 291459, 'song_url': 'https://open.spotify.com/track/2YZZFwARteC3gM1aEgHHMr', 'song_added_at': '2024-08-18T16:10:50Z', 'album_id': '37evPVtdfVL0X4Sji9tQdu', 'artist_id': '70B80Lwx2sxti0M1Ng9e8K'}, {'song_id': '0hwlEWBrraTWI9PTNzG0RJ', 'song_name': 'Cheliya', 'song_duration': 340331, 'song_url': 'https://open.spotify.com/track/0hwlEWBrraTWI9PTNzG0RJ', 'song_added_at': '2024-08-18T16:10:50Z', 'album_id': '37evPVtdfVL0X4Sji9tQdu', 'artist_id': '3K9qRRRqtuxgBRLxRCxpDl'}, {'song_id': '1llCrHsp3meUV30YTiTwpY', 'song_name': 'Premante', 'song_duration': 372940, 'song_url': 'https://open.spotify.com/track/1llCrHsp3meUV30YTiTwpY', 'song_added_at': '2024-08-18T16:10:50Z', 'album_id': '37evPVtdfVL0X4Sji9tQdu', 'artist_id': '1HUZ6vfsSWpfLoxjgDavEB'}, {'song_id': '1pHttWyIwIbFu9vVjsjOUr', 'song_name': 'Aaduvari', 'song_duration': 180876, 'song_url': 'https://open.spotify.com/track/1pHttWyIwIbFu9vVjsjOUr', 'song_added_at': '2024-08-18T16:10:50Z', 'album_id': '37evPVtdfVL0X4Sji9tQdu', 'artist_id': '3zry1HzVn8WqSFHigzZ8bx'}, {'song_id': '4DS8arJWnkpetpBg72P0nJ', 'song_name': 'Holi Holi', 'song_duration': 311413, 'song_url': 'https://open.spotify.com/track/4DS8arJWnkpetpBg72P0nJ', 'song_added_at': '2024-08-18T16:10:50Z', 'album_id': '37evPVtdfVL0X4Sji9tQdu', 'artist_id': '3NzhVoa20crNtp1p4zE8um'}, {'song_id': '5ReOjb2X6TCkMfYoHuVW1b', 'song_name': 'Na Roja Nuvve', 'song_duration': 242526, 'song_url': 'https://open.spotify.com/track/5ReOjb2X6TCkMfYoHuVW1b', 'song_added_at': '2024-08-18T16:11:09Z', 'album_id': '78bohc0Dzw7AoPpqVn9rsl', 'artist_id': '50iBEPSw6kQ8GQkumXz7XZ'}, {'song_id': '3nCqpSpwxuO4gYF1wGS6WM', 'song_name': 'Aradhya', 'song_duration': 282222, 'song_url': 'https://open.spotify.com/track/3nCqpSpwxuO4gYF1wGS6WM', 'song_added_at': '2024-08-18T16:11:09Z', 'album_id': '78bohc0Dzw7AoPpqVn9rsl', 'artist_id': '50iBEPSw6kQ8GQkumXz7XZ'}, {'song_id': '6Zp14O0N7iNLTrKYSOsOJh', 'song_name': 'Kushi Title Song', 'song_duration': 210000, 'song_url': 'https://open.spotify.com/track/6Zp14O0N7iNLTrKYSOsOJh', 'song_added_at': '2024-08-18T16:11:09Z', 'album_id': '78bohc0Dzw7AoPpqVn9rsl', 'artist_id': '50iBEPSw6kQ8GQkumXz7XZ'}, {'song_id': '4uZ5kNUtXpb8B57taLXVyT', 'song_name': 'Yedhaki Oka Gaayam', 'song_duration': 230076, 'song_url': 'https://open.spotify.com/track/4uZ5kNUtXpb8B57taLXVyT', 'song_added_at': '2024-08-18T16:11:09Z', 'album_id': '78bohc0Dzw7AoPpqVn9rsl', 'artist_id': '50iBEPSw6kQ8GQkumXz7XZ'}, {'song_id': '36WCfBpLBpBKCzWB8pgvEj', 'song_name': 'Osi Pellama', 'song_duration': 218250, 'song_url': 'https://open.spotify.com/track/36WCfBpLBpBKCzWB8pgvEj', 'song_added_at': '2024-08-18T16:11:09Z', 'album_id': '78bohc0Dzw7AoPpqVn9rsl', 'artist_id': '50iBEPSw6kQ8GQkumXz7XZ'}, {'song_id': '4ZNIkO2j6K2c0Nm8zWXmdn', 'song_name': 'Tillu Anna DJ Pedithe', 'song_duration': 183500, 'song_url': 'https://open.spotify.com/track/4ZNIkO2j6K2c0Nm8zWXmdn', 'song_added_at': '2024-08-18T16:11:26Z', 'album_id': '3loo3ZQ43Rsu0FdtorNZE0', 'artist_id': '4A2XSc4OJjuPY4l6NjnrDj'}, {'song_id': '3NdQpAhK5s42vu3do3KSBT', 'song_name': 'Ticket Eh Konakunda', 'song_duration': 189966, 'song_url': 'https://open.spotify.com/track/3NdQpAhK5s42vu3do3KSBT', 'song_added_at': '2024-08-18T16:11:37Z', 'album_id': '5oNL1ay25NKeMieYCFwhci', 'artist_id': '4A2XSc4OJjuPY4l6NjnrDj'}, {'song_id': '0S9j9OAG3KjmBg4j9XzFcC', 'song_name': 'Radhika', 'song_duration': 188648, 'song_url': 'https://open.spotify.com/track/0S9j9OAG3KjmBg4j9XzFcC', 'song_added_at': '2024-08-18T16:11:37Z', 'album_id': '7ujJhfGKy2qKe2OBQqw173', 'artist_id': '4A2XSc4OJjuPY4l6NjnrDj'}, {'song_id': '3nHm9xxmzEbLigsaigMhdk', 'song_name': 'Oh My Lily', 'song_duration': 201923, 'song_url': 'https://open.spotify.com/track/3nHm9xxmzEbLigsaigMhdk', 'song_added_at': '2024-08-18T16:11:37Z', 'album_id': '7E7U9TkPPbPeAg4EnkdYW8', 'artist_id': '13M1OXRslYiaRoeaUx75uY'}, {'song_id': '5TbrSBo3ob5QLD9y0YowJZ', 'song_name': 'Edo Edo', 'song_duration': 301668, 'song_url': 'https://open.spotify.com/track/5TbrSBo3ob5QLD9y0YowJZ', 'song_added_at': '2024-08-18T16:11:54Z', 'album_id': '2KaGqPKoMOwa9jyDClvyZE', 'artist_id': '2hNON05iexckgWGTpiOg9L'}, {'song_id': '13sMxrwVZsewW7TWo0py5x', 'song_name': 'Chi Chi CHi', 'song_duration': 209042, 'song_url': 'https://open.spotify.com/track/13sMxrwVZsewW7TWo0py5x', 'song_added_at': '2024-08-18T16:11:54Z', 'album_id': '2KaGqPKoMOwa9jyDClvyZE', 'artist_id': '00hL0oJD4pWef0kPYIaSTy'}, {'song_id': '0dyKAXGZbr2YlYfGaxwlix', 'song_name': 'Ela Ela', 'song_duration': 243142, 'song_url': 'https://open.spotify.com/track/0dyKAXGZbr2YlYfGaxwlix', 'song_added_at': '2024-08-18T16:11:54Z', 'album_id': '2KaGqPKoMOwa9jyDClvyZE', 'artist_id': '2hNON05iexckgWGTpiOg9L'}, {'song_id': '0GdqslyQxu5GcAQSggao0j', 'song_name': 'Nuvvante Naaku Istam', 'song_duration': 249015, 'song_url': 'https://open.spotify.com/track/0GdqslyQxu5GcAQSggao0j', 'song_added_at': '2024-08-18T16:11:54Z', 'album_id': '2KaGqPKoMOwa9jyDClvyZE', 'artist_id': '00hL0oJD4pWef0kPYIaSTy'}, {'song_id': '7DHZqJ8XQSEvIXs9BjriPU', 'song_name': 'Nindu Godari', 'song_duration': 232699, 'song_url': 'https://open.spotify.com/track/7DHZqJ8XQSEvIXs9BjriPU', 'song_added_at': '2024-08-18T16:11:54Z', 'album_id': '2KaGqPKoMOwa9jyDClvyZE', 'artist_id': '00hL0oJD4pWef0kPYIaSTy'}, {'song_id': '5avXQ60kyevSUDcXJxiaMQ', 'song_name': 'Nuvvante Naaku Istam', 'song_duration': 78278, 'song_url': 'https://open.spotify.com/track/5avXQ60kyevSUDcXJxiaMQ', 'song_added_at': '2024-08-18T16:11:54Z', 'album_id': '2KaGqPKoMOwa9jyDClvyZE', 'artist_id': '2hNON05iexckgWGTpiOg9L'}, {'song_id': '08siM57VJCV7lGg6JWmB3s', 'song_name': 'Chinni Chinni', 'song_duration': 255455, 'song_url': 'https://open.spotify.com/track/08siM57VJCV7lGg6JWmB3s', 'song_added_at': '2024-08-18T16:11:54Z', 'album_id': '2KaGqPKoMOwa9jyDClvyZE', 'artist_id': '2ae6PxICSOZHvjqiCcgon8'}, {'song_id': '28xt5x1wwoMfVYI9zfIwRx', 'song_name': 'Oh Sita Hey Rama', 'song_duration': 246412, 'song_url': 'https://open.spotify.com/track/28xt5x1wwoMfVYI9zfIwRx', 'song_added_at': '2024-08-18T16:12:06Z', 'album_id': '5d0eh1FoU7tOYEnHLohjjv', 'artist_id': '0rL4uL3xfYOt2p7NHhS8qr'}, {'song_id': '2rDPTKSWgUbFuV1jFzPqvE', 'song_name': 'Kaanunna Kalyanam', 'song_duration': 232513, 'song_url': 'https://open.spotify.com/track/2rDPTKSWgUbFuV1jFzPqvE', 'song_added_at': '2024-08-18T16:12:06Z', 'album_id': '5d0eh1FoU7tOYEnHLohjjv', 'artist_id': '0rL4uL3xfYOt2p7NHhS8qr'}, {'song_id': '0sd5MZPkgjHzTlrrZE4XDk', 'song_name': 'Yevarini Adaganu', 'song_duration': 148349, 'song_url': 'https://open.spotify.com/track/0sd5MZPkgjHzTlrrZE4XDk', 'song_added_at': '2024-08-18T16:12:06Z', 'album_id': '5d0eh1FoU7tOYEnHLohjjv', 'artist_id': '0rL4uL3xfYOt2p7NHhS8qr'}, {'song_id': '63NdWczrPCYGWKY1RV4Zbh', 'song_name': 'Oh Prema', 'song_duration': 208679, 'song_url': 'https://open.spotify.com/track/63NdWczrPCYGWKY1RV4Zbh', 'song_added_at': '2024-08-18T16:12:06Z', 'album_id': '5d0eh1FoU7tOYEnHLohjjv', 'artist_id': '0rL4uL3xfYOt2p7NHhS8qr'}, {'song_id': '6DH51oJbucwELZLfTYAZkT', 'song_name': 'Tharali Tharali', 'song_duration': 77977, 'song_url': 'https://open.spotify.com/track/6DH51oJbucwELZLfTYAZkT', 'song_added_at': '2024-08-18T16:12:06Z', 'album_id': '5d0eh1FoU7tOYEnHLohjjv', 'artist_id': '0rL4uL3xfYOt2p7NHhS8qr'}, {'song_id': '54EJAhkEo4ERDUVQMoWdtb', 'song_name': 'Nene Aa Nene', 'song_duration': 238711, 'song_url': 'https://open.spotify.com/track/54EJAhkEo4ERDUVQMoWdtb', 'song_added_at': '2024-08-18T16:12:06Z', 'album_id': '5d0eh1FoU7tOYEnHLohjjv', 'artist_id': '0rL4uL3xfYOt2p7NHhS8qr'}, {'song_id': '04RL413v1BqfHMDNCmKBAI', 'song_name': 'Chitthi', 'song_duration': 169500, 'song_url': 'https://open.spotify.com/track/04RL413v1BqfHMDNCmKBAI', 'song_added_at': '2024-08-18T16:12:06Z', 'album_id': '3OE7LZ7rSmnpDz0L5NaTJR', 'artist_id': '0rL4uL3xfYOt2p7NHhS8qr'}, {'song_id': '1qnB1JUsGwOK5VnZflixBB', 'song_name': 'Uppongela Godavari', 'song_duration': 294013, 'song_url': 'https://open.spotify.com/track/1qnB1JUsGwOK5VnZflixBB', 'song_added_at': '2024-08-18T16:12:18Z', 'album_id': '2OyJ5P81elIOSPFSj2gnkE', 'artist_id': '2ae6PxICSOZHvjqiCcgon8'}, {'song_id': '0OfaxrkK5wNf6Gotdph5Jz', 'song_name': 'Manasavacha', 'song_duration': 287613, 'song_url': 'https://open.spotify.com/track/0OfaxrkK5wNf6Gotdph5Jz', 'song_added_at': '2024-08-18T16:12:18Z', 'album_id': '2OyJ5P81elIOSPFSj2gnkE', 'artist_id': '0mV4UQ0gHg59AAUtg968pX'}, {'song_id': '4MD9HLsY2JheBumbYjEbTV', 'song_name': 'Tippulu Tappulu', 'song_duration': 262013, 'song_url': 'https://open.spotify.com/track/4MD9HLsY2JheBumbYjEbTV', 'song_added_at': '2024-08-18T16:12:18Z', 'album_id': '2OyJ5P81elIOSPFSj2gnkE', 'artist_id': '0oOet2f43PA68X5RxKobEy'}, {'song_id': '1UBM4j8bzMnQaKHDaairxW', 'song_name': 'Manasa Gelupu', 'song_duration': 245200, 'song_url': 'https://open.spotify.com/track/1UBM4j8bzMnQaKHDaairxW', 'song_added_at': '2024-08-18T16:12:18Z', 'album_id': '2OyJ5P81elIOSPFSj2gnkE', 'artist_id': '1SJOL9HJ08YOn92lFcYf8a'}, {'song_id': '46IqUkQTOH7aEaZFUcpSON', 'song_name': 'Andangalena', 'song_duration': 260013, 'song_url': 'https://open.spotify.com/track/46IqUkQTOH7aEaZFUcpSON', 'song_added_at': '2024-08-18T16:12:18Z', 'album_id': '2OyJ5P81elIOSPFSj2gnkE', 'artist_id': '72AhOfYH44654ISqbuwdEZ'}, {'song_id': '7l5fS4lbkdwzteVyE6s2IO', 'song_name': 'Ramachakkani Sitha', 'song_duration': 231973, 'song_url': 'https://open.spotify.com/track/7l5fS4lbkdwzteVyE6s2IO', 'song_added_at': '2024-08-18T16:12:18Z', 'album_id': '2OyJ5P81elIOSPFSj2gnkE', 'artist_id': '2Ah48tA0TPqph0m9snNNxM'}, {'song_id': '16beX6njtdasRvgm86HEg6', 'song_name': 'Uppongela Godavari', 'song_duration': 107746, 'song_url': 'https://open.spotify.com/track/16beX6njtdasRvgm86HEg6', 'song_added_at': '2024-08-18T16:12:18Z', 'album_id': '2OyJ5P81elIOSPFSj2gnkE', 'artist_id': '2Ah48tA0TPqph0m9snNNxM'}, {'song_id': '2g5t70UUP6nPpyZdyQQJz2', 'song_name': 'Yamunatheeram', 'song_duration': 249826, 'song_url': 'https://open.spotify.com/track/2g5t70UUP6nPpyZdyQQJz2', 'song_added_at': '2024-08-18T16:12:27Z', 'album_id': '7qe9NgxK1B9zNTyZLUF5pG', 'artist_id': '2NoJ7NuNs9nyj8Thoh1kbu'}, {'song_id': '7o6iBqzR1iIN8X2IpvLmVw', 'song_name': 'Vachhe Vachhe', 'song_duration': 273933, 'song_url': 'https://open.spotify.com/track/7o6iBqzR1iIN8X2IpvLmVw', 'song_added_at': '2024-08-18T16:12:27Z', 'album_id': '7qe9NgxK1B9zNTyZLUF5pG', 'artist_id': '0oOet2f43PA68X5RxKobEy'}, {'song_id': '4k6N1wRZ5Im7KmbINgBdO3', 'song_name': 'Nuvvena', 'song_duration': 293840, 'song_url': 'https://open.spotify.com/track/4k6N1wRZ5Im7KmbINgBdO3', 'song_added_at': '2024-08-18T16:12:27Z', 'album_id': '7qe9NgxK1B9zNTyZLUF5pG', 'artist_id': '0oOet2f43PA68X5RxKobEy'}, {'song_id': '76WzfVTkixrm5P6oupw4KY', 'song_name': 'Charumati', 'song_duration': 248573, 'song_url': 'https://open.spotify.com/track/76WzfVTkixrm5P6oupw4KY', 'song_added_at': '2024-08-18T16:12:27Z', 'album_id': '7qe9NgxK1B9zNTyZLUF5pG', 'artist_id': '2L16nDKTxhFGaDriR2AHTB'}, {'song_id': '2zMR9S3JRW0fplrVCAWIDf', 'song_name': 'Telisi Telisi', 'song_duration': 267280, 'song_url': 'https://open.spotify.com/track/2zMR9S3JRW0fplrVCAWIDf', 'song_added_at': '2024-08-18T16:12:27Z', 'album_id': '7qe9NgxK1B9zNTyZLUF5pG', 'artist_id': '0oOet2f43PA68X5RxKobEy'}, {'song_id': '6U8Gvg0lqTZzrSOgIZcf0Z', 'song_name': 'Yedaloganam', 'song_duration': 296653, 'song_url': 'https://open.spotify.com/track/6U8Gvg0lqTZzrSOgIZcf0Z', 'song_added_at': '2024-08-18T16:12:27Z', 'album_id': '7qe9NgxK1B9zNTyZLUF5pG', 'artist_id': '2NoJ7NuNs9nyj8Thoh1kbu'}, {'song_id': '1DpG1xxz90gjxjmbuNc4Z7', 'song_name': 'Nuvante Nakistamani', 'song_duration': 300774, 'song_url': 'https://open.spotify.com/track/1DpG1xxz90gjxjmbuNc4Z7', 'song_added_at': '2024-08-18T16:12:38Z', 'album_id': '5pZ7o500CAKbB4ciJVBNyl', 'artist_id': '6aQ5LDX0WlnyDLI8TGU0wK'}, {'song_id': '6kFb1tl29cc8sa9Sr178af', 'song_name': 'Dhim Dhinaktari', 'song_duration': 262172, 'song_url': 'https://open.spotify.com/track/6kFb1tl29cc8sa9Sr178af', 'song_added_at': '2024-08-18T16:12:38Z', 'album_id': '5pZ7o500CAKbB4ciJVBNyl', 'artist_id': '1SJOL9HJ08YOn92lFcYf8a'}, {'song_id': '0olcG4suN6NWmimWuuvOMU', 'song_name': 'So Much To', 'song_duration': 74626, 'song_url': 'https://open.spotify.com/track/0olcG4suN6NWmimWuuvOMU', 'song_added_at': '2024-08-18T16:12:38Z', 'album_id': '5pZ7o500CAKbB4ciJVBNyl', 'artist_id': '6aQ5LDX0WlnyDLI8TGU0wK'}, {'song_id': '4Y3HG8mmJYpHN05X7SWWHI', 'song_name': 'Devudey Dhigi', 'song_duration': 238571, 'song_url': 'https://open.spotify.com/track/4Y3HG8mmJYpHN05X7SWWHI', 'song_added_at': '2024-08-18T16:12:38Z', 'album_id': '5pZ7o500CAKbB4ciJVBNyl', 'artist_id': '4fEkbug6kZzzJ8eYX6Kbbp'}, {'song_id': '4mIOdOh49kfRSZBwvylulK', 'song_name': 'Nee Tholisariga', 'song_duration': 290966, 'song_url': 'https://open.spotify.com/track/4mIOdOh49kfRSZBwvylulK', 'song_added_at': '2024-08-18T16:12:38Z', 'album_id': '5pZ7o500CAKbB4ciJVBNyl', 'artist_id': '2hNON05iexckgWGTpiOg9L'}, {'song_id': '0xbSPPjXQkxUZSkj7n7C34', 'song_name': 'Mehabooba', 'song_duration': 246212, 'song_url': 'https://open.spotify.com/track/0xbSPPjXQkxUZSkj7n7C34', 'song_added_at': '2024-08-18T16:12:38Z', 'album_id': '5pZ7o500CAKbB4ciJVBNyl', 'artist_id': '3NzhVoa20crNtp1p4zE8um'}, {'song_id': '4A6j0Du0IrhL5F8smYVMTq', 'song_name': 'Emainadho Emo', 'song_duration': 116550, 'song_url': 'https://open.spotify.com/track/4A6j0Du0IrhL5F8smYVMTq', 'song_added_at': '2024-08-18T16:12:38Z', 'album_id': '5pZ7o500CAKbB4ciJVBNyl', 'artist_id': '00hL0oJD4pWef0kPYIaSTy'}, {'song_id': '23TzyhGzuYdpnJeuiXJBtN', 'song_name': 'Diri Diri', 'song_duration': 261245, 'song_url': 'https://open.spotify.com/track/23TzyhGzuYdpnJeuiXJBtN', 'song_added_at': '2024-08-18T16:12:38Z', 'album_id': '5pZ7o500CAKbB4ciJVBNyl', 'artist_id': '4fEkbug6kZzzJ8eYX6Kbbp'}, {'song_id': '1ifMH14KizpUxIdRVyPsSZ', 'song_name': 'Niluvaddham', 'song_duration': 357336, 'song_url': 'https://open.spotify.com/track/1ifMH14KizpUxIdRVyPsSZ', 'song_added_at': '2024-08-18T16:12:47Z', 'album_id': '5I3dEH9cXdYmo8MVIdOkxO', 'artist_id': '0LSPREIgGMZXCuKVel7LVD'}, {'song_id': '4EztIh7yvgYs9YLCvxT8ku', 'song_name': 'Something Something', 'song_duration': 332906, 'song_url': 'https://open.spotify.com/track/4EztIh7yvgYs9YLCvxT8ku', 'song_added_at': '2024-08-18T16:12:47Z', 'album_id': '5I3dEH9cXdYmo8MVIdOkxO', 'artist_id': '0PykiHCcDsMPRV7s67qZ1B'}, {'song_id': '69PuGOoNWxd2hM0tsrCa2O', 'song_name': 'Ghal Ghal', 'song_duration': 319563, 'song_url': 'https://open.spotify.com/track/69PuGOoNWxd2hM0tsrCa2O', 'song_added_at': '2024-08-18T16:12:47Z', 'album_id': '5I3dEH9cXdYmo8MVIdOkxO', 'artist_id': '2ae6PxICSOZHvjqiCcgon8'}, {'song_id': '4b4xkbpRpA8jHbP8GVLYWR', 'song_name': 'Chandrullo Unde', 'song_duration': 255292, 'song_url': 'https://open.spotify.com/track/4b4xkbpRpA8jHbP8GVLYWR', 'song_added_at': '2024-08-18T16:12:47Z', 'album_id': '5I3dEH9cXdYmo8MVIdOkxO', 'artist_id': '1SJOL9HJ08YOn92lFcYf8a'}, {'song_id': '3Gmq2pQZNo5TqrobE10WgA', 'song_name': 'Pari Poke Pitta', 'song_duration': 217619, 'song_url': 'https://open.spotify.com/track/3Gmq2pQZNo5TqrobE10WgA', 'song_added_at': '2024-08-18T16:12:47Z', 'album_id': '5I3dEH9cXdYmo8MVIdOkxO', 'artist_id': '40Ce6P4AGMq3NXCDXVSZaa'}, {'song_id': '6OJemp4sHmpogO2ieTATsq', 'song_name': 'Padam Kadala', 'song_duration': 68541, 'song_url': 'https://open.spotify.com/track/6OJemp4sHmpogO2ieTATsq', 'song_added_at': '2024-08-18T16:12:47Z', 'album_id': '5I3dEH9cXdYmo8MVIdOkxO', 'artist_id': '6CWBs7ul78QwnBrcOCwhf5'}, {'song_id': '4FexaCwCrxQ9OErHZiLlWh', 'song_name': 'Adirey Adirey', 'song_duration': 257162, 'song_url': 'https://open.spotify.com/track/4FexaCwCrxQ9OErHZiLlWh', 'song_added_at': '2024-08-18T16:12:47Z', 'album_id': '5I3dEH9cXdYmo8MVIdOkxO', 'artist_id': '3cowxATurZfjWsJC4uEHsl'}, {'song_id': '28GsFcWboBzq0kVMXl0cDL', 'song_name': 'Manasa Manasa', 'song_duration': 253411, 'song_url': 'https://open.spotify.com/track/28GsFcWboBzq0kVMXl0cDL', 'song_added_at': '2024-08-18T16:12:58Z', 'album_id': '67FATbnVWtXgD9TF6OGb3P', 'artist_id': '7qjJw7ZM2ekDSahLXPjIlN'}, {'song_id': '0eBqUmGdSPM922MHW1wGem', 'song_name': 'Guche Gulabi', 'song_duration': 282476, 'song_url': 'https://open.spotify.com/track/0eBqUmGdSPM922MHW1wGem', 'song_added_at': '2024-08-18T16:12:58Z', 'album_id': '67FATbnVWtXgD9TF6OGb3P', 'artist_id': '4IKVDbCSBTxBeAsMKjAuTs'}, {'song_id': '15aagpaC5XENZJUYW954Ot', 'song_name': 'Zindagi', 'song_duration': 245763, 'song_url': 'https://open.spotify.com/track/15aagpaC5XENZJUYW954Ot', 'song_added_at': '2024-08-18T16:12:58Z', 'album_id': '67FATbnVWtXgD9TF6OGb3P', 'artist_id': '2qE6XvN9lbEFGFfQOREsr0'}, {'song_id': '0pCXbJ3lbtinCZnwg1CYDC', 'song_name': 'Leharaayi', 'song_duration': 245093, 'song_url': 'https://open.spotify.com/track/0pCXbJ3lbtinCZnwg1CYDC', 'song_added_at': '2024-08-18T16:12:58Z', 'album_id': '67FATbnVWtXgD9TF6OGb3P', 'artist_id': '7qjJw7ZM2ekDSahLXPjIlN'}, {'song_id': '0WpVe4KIQpuCsAdzG3FubQ', 'song_name': 'Chitti Adugu', 'song_duration': 2555

In [15]:
import pandas as pd
album_df = pd.DataFrame(album)
artists_df = pd.DataFrame(artists)
songs_df = pd.DataFrame(song_list)

In [16]:
album_df.head()

,album_id,album_name,album_release_date,album_total_tracks,album_spotify_url
0,2eASY2UZa4O8pdXvK9SNgC,Chandamama,2007-09-06,6,https://open.spotify.com/track/32faUN4IsCs1wk1...
1,2eASY2UZa4O8pdXvK9SNgC,Chandamama,2007-09-06,6,https://open.spotify.com/track/4yDzLrYRH1vMSI1...
2,2eASY2UZa4O8pdXvK9SNgC,Chandamama,2007-09-06,6,https://open.spotify.com/track/1DPRAIq9V0r2UPw...
3,0oqXFsTVJInCqJJJAn7wel,Radhe Shyam (Telugu),2022-03-12,7,https://open.spotify.com/track/5C8b6OQlsIOtpbf...
4,0oqXFsTVJInCqJJJAn7wel,Radhe Shyam (Telugu),2022-03-12,7,https://open.spotify.com/track/56dpwomaj1YnKZ0...

In [17]:
artists_df.head()

,artist_id,artist_name,external_url
0,5as8A4G47Ohu9NSWs3Je8U,Asha Bhosle,https://api.spotify.com/v1/artists/5as8A4G47Oh...
1,579pH2PjdCVSkAyFBv2Z8g,K M Radhakrishnan,https://api.spotify.com/v1/artists/579pH2PjdCV...
2,0BDs2eNYNZvlMnnlijsfoL,Jessi Gift,https://api.spotify.com/v1/artists/0BDs2eNYNZv...
3,3QL2xVnI7n5Fng1l4e56AP,Mamta Mohandas,https://api.spotify.com/v1/artists/3QL2xVnI7n5...
4,1QvyquqkuuwUzdszyoKIy4,Haricharan,https://api.spotify.com/v1/artists/1Qvyquqkuuw...

In [18]:
songs_df.head()

,song_id,song_name,song_duration,song_url,song_added_at,album_id,artist_id
0,32faUN4IsCs1wk1ljIQr9C,Naalo Oohalaku,273776,https://open.spotify.com/track/32faUN4IsCs1wk1...,2024-08-18T16:09:43Z,2eASY2UZa4O8pdXvK9SNgC,5as8A4G47Ohu9NSWs3Je8U
1,4yDzLrYRH1vMSI1qjR8ymb,Sakkubayiney,274454,https://open.spotify.com/track/4yDzLrYRH1vMSI1...,2024-08-18T16:09:46Z,2eASY2UZa4O8pdXvK9SNgC,0BDs2eNYNZvlMnnlijsfoL
2,1DPRAIq9V0r2UPw4xA1iFf,Mukku Pye Muddu,278864,https://open.spotify.com/track/1DPRAIq9V0r2UPw...,2024-08-18T16:09:50Z,2eASY2UZa4O8pdXvK9SNgC,1QvyquqkuuwUzdszyoKIy4
3,5C8b6OQlsIOtpbf6DCBkKk,Sanchari,268000,https://open.spotify.com/track/5C8b6OQlsIOtpbf...,2024-08-18T16:10:00Z,0oqXFsTVJInCqJJJAn7wel,4zCH9qm4R2DADamUHMCa6O
4,56dpwomaj1YnKZ0L4b33hN,Nagumomu Thaarale,294115,https://open.spotify.com/track/56dpwomaj1YnKZ0...,2024-08-18T16:10:04Z,0oqXFsTVJInCqJJJAn7wel,7qjJw7ZM2ekDSahLXPjIlN

# Transformation

### Remove duplicates

In [19]:
album_df = album_df.drop_duplicates(subset = ['album_id'])
artists_df = artists_df.drop_duplicates(subset = ['artist_id'])

### convert string date to Date Time

In [20]:
album_df['album_release_date'] = pd.to_datetime(album_df['album_release_date'], errors='coerce')

In [21]:
songs_df['song_added_at'] = pd.to_datetime(songs_df['song_added_at'], errors='coerce')

In [22]:
album_df.head()

,album_id,album_name,album_release_date,album_total_tracks,album_spotify_url
0,2eASY2UZa4O8pdXvK9SNgC,Chandamama,2007-09-06,6,https://open.spotify.com/track/32faUN4IsCs1wk1...
3,0oqXFsTVJInCqJJJAn7wel,Radhe Shyam (Telugu),2022-03-12,7,https://open.spotify.com/track/5C8b6OQlsIOtpbf...
10,37evPVtdfVL0X4Sji9tQdu,Kushi,2001-03-27,6,https://open.spotify.com/track/1ha2Dvv2vVyIbQU...
16,78bohc0Dzw7AoPpqVn9rsl,Kushi (Telugu),2023-08-29,5,https://open.spotify.com/track/5ReOjb2X6TCkMfY...
21,3loo3ZQ43Rsu0FdtorNZE0,DJ Tillu,2022-01-06,1,https://open.spotify.com/track/4ZNIkO2j6K2c0Nm...

In [23]:
artists_df.head()

,artist_id,artist_name,external_url
0,5as8A4G47Ohu9NSWs3Je8U,Asha Bhosle,https://api.spotify.com/v1/artists/5as8A4G47Oh...
1,579pH2PjdCVSkAyFBv2Z8g,K M Radhakrishnan,https://api.spotify.com/v1/artists/579pH2PjdCV...
2,0BDs2eNYNZvlMnnlijsfoL,Jessi Gift,https://api.spotify.com/v1/artists/0BDs2eNYNZv...
3,3QL2xVnI7n5Fng1l4e56AP,Mamta Mohandas,https://api.spotify.com/v1/artists/3QL2xVnI7n5...
4,1QvyquqkuuwUzdszyoKIy4,Haricharan,https://api.spotify.com/v1/artists/1Qvyquqkuuw...

In [24]:
songs_df.head()

,song_id,song_name,song_duration,song_url,song_added_at,album_id,artist_id
0,32faUN4IsCs1wk1ljIQr9C,Naalo Oohalaku,273776,https://open.spotify.com/track/32faUN4IsCs1wk1...,2024-08-18 16:09:43+00:00,2eASY2UZa4O8pdXvK9SNgC,5as8A4G47Ohu9NSWs3Je8U
1,4yDzLrYRH1vMSI1qjR8ymb,Sakkubayiney,274454,https://open.spotify.com/track/4yDzLrYRH1vMSI1...,2024-08-18 16:09:46+00:00,2eASY2UZa4O8pdXvK9SNgC,0BDs2eNYNZvlMnnlijsfoL
2,1DPRAIq9V0r2UPw4xA1iFf,Mukku Pye Muddu,278864,https://open.spotify.com/track/1DPRAIq9V0r2UPw...,2024-08-18 16:09:50+00:00,2eASY2UZa4O8pdXvK9SNgC,1QvyquqkuuwUzdszyoKIy4
3,5C8b6OQlsIOtpbf6DCBkKk,Sanchari,268000,https://open.spotify.com/track/5C8b6OQlsIOtpbf...,2024-08-18 16:10:00+00:00,0oqXFsTVJInCqJJJAn7wel,4zCH9qm4R2DADamUHMCa6O
4,56dpwomaj1YnKZ0L4b33hN,Nagumomu Thaarale,294115,https://open.spotify.com/track/56dpwomaj1YnKZ0...,2024-08-18 16:10:04+00:00,0oqXFsTVJInCqJJJAn7wel,7qjJw7ZM2ekDSahLXPjIlN